/* Context-aware offline dialogue. No message leaves the browser. */
class CompanionDialogue{
 constructor(){this.name='';this.topic='';this.gentle=false;this.counts={};this.awaiting='';this.profile={name:'',address:'',identity:'学生',context:'',needs:[]};this.memory={likes:[],dislikes:[],plans:[]};this.history=[];this.recent=[]}
 setProfile(profile={}){this.profile={...this.profile,...profile};if(this.profile.name&&!this.name)this.name=this.profile.name}
 address(){return this.profile.address?.trim()||this.name||'你'}
 pick(key,lines){const i=this.counts[key]||0;this.counts[key]=i+1;return lines[i%lines.length]}
 remember(bucket,value){value=value.replace(/[。！!？?，,].*$/,'').trim().slice(0,30);if(!value)return;const list=this.memory[bucket];if(!list.includes(value))list.unshift(value);list.splice(4)}
 memorySummary(){const p=[];if(this.name)p.push(`称呼：${this.name}`);if(this.memory.likes[0])p.push(`喜欢：${this.memory.likes[0]}`);if(this.memory.plans[0])p.push(`待办：${this.memory.plans[0]}`);return p}
 context(){return{profile:this.profile,topic:this.topic,awaiting:this.awaiting,memory:this.memory,history:this.history.slice(-8)}}
 begin(text){this.history.push({role:'user',text:text.slice(0,500)});this.history=this.history.slice(-12)}
 finish(text,mood='listening',topic=this.topic,suggestions=[],awaiting=''){if(this.recent.includes(text))text=this.pick('repeat-repair',[`我换个问法。${text}`,`刚才那句太像套话了。具体一点：${suggestions[0]||'你最在意的是哪一部分？'}`]);this.topic=topic;this.awaiting=awaiting;this.recent.push(text);this.recent=this.recent.slice(-5);this.history.push({role:'assistant',text});this.history=this.history.slice(-12);return{text,mood,topic,suggestions}}
 keyDetail(s){const clauses=s.split(/[，。！？；\n]/).map(x=>x.trim()).filter(x=>x.length>=4);return(clauses.sort((a,b)=>b.length-a.length)[0]||s).slice(0,32)}
 study(raw){const s=raw.replace(/\s+/g,'').replace(/−/g,'-').replace(/×/g,'*').replace(/÷/g,'/');const m=s.match(/^([+-]?\d*\.?\d*)x([+-]\d+(?:\.\d+)?)?=([+-]?\d+(?:\.\d+)?)$/i);if(m){let a=m[1];a=a===''||a==='+'?1:a==='-'?-1:Number(a);const b=Number(m[2]||0),c=Number(m[3]);if(a){const moved=c-b,x=moved/a;return this.finish(`先处理常数项：${a}x = ${moved}。两边同时除以 ${a}，得到 x = ${Number(x.toFixed(6))}。代回原式会得到 ${c}。你原来卡在移项、除法，还是验算？`,'focused','study',['移项这一步','除法这一步','给我一道更难的变式'],'study-step')}}const n=s.match(/^(-?\d+(?:\.\d+)?)([+\-*/])(-?\d+(?:\.\d+)?)=?$/);if(n){const a=Number(n[1]),b=Number(n[3]),op=n[2];if(op==='/'&&b===0)return this.finish('除数为 0，算式没有定义。先核对题目是否抄漏了条件。','focused','study',['检查题目','换一道题']);const result={'+':a+b,'-':a-b,'*':a*b,'/':a/b}[op];return this.finish(`结果是 ${Number(result.toFixed(8))}。如果这是作业题，别只留下答案：写出运算顺序或估算范围，才能看出你真的掌握了。`,'focused','study',['给我一道变式题','检查我的步骤','提高难度'])}if(/作文|议论文|阅读理解|概括|中心思想/.test(raw))return this.finish('先把任务拆成三层：题干要求你做什么，材料反复强调什么，你准备给出什么判断。把原题和初步判断发来，我会检查证据是否撑得住结论。','focused','study',['帮我拆题干','检查论证','只提示第一步'],'study-text');if(/英语|单词|语法|时态|完形/.test(raw))return this.finish('请把完整句子、选项和你的选择一起发来。单看空格容易误判，我会先检查时间标志、主干结构和语义约束。','focused','study',['检查一个句子','区分两个选项','给我一道进阶练习'],'study-language');return this.finish('把题目、你已经做过的步骤、以及最不确定的一处一起发来。我会先检查条件是否充分，再给下一步。','focused','study',['整理已知条件','检查我的推理','只提示下一步'],'study-open')}
 followUp(s){if(this.awaiting==='choice-role'&&/(听|建议|分析|陪|问|列条件|风险)/.test(s))return this.finish(/建议|分析|列条件|风险/.test(s)?'好。先给我两个信息：你真正想保住什么，以及最坏的可接受结果是什么。知道这两点，建议才不会只剩空话。':'好，我先听。按你觉得重要的顺序讲，不需要把经过整理得很漂亮。','focused','decision',/建议|分析|列条件|风险/.test(s)?['我最想保住…','最坏能接受…','先列两个选项']:['事情是这样开始的…','最难受的是…'],'decision-detail');if(this.awaiting==='fact-feeling'&&/(事实|发生|做了|说了)/.test(s))return this.finish('先只记录第三个人能观察到的部分：谁在什么时候说了什么、做了什么。等事实摆清楚，再判断对方的动机，误差会小很多。','focused','relationship',['当时他说的是…','我当时做了…','再分析他的动机'],'relationship-fact');if(this.awaiting==='fact-feeling'&&/(感受|难受|生气|委屈|失望)/.test(s))return this.finish('先不急着判断谁对。你的感受更接近被忽视、被误解、被控制，还是边界被越过？不同答案需要不同的下一步。','quiet','relationship',['被忽视','被误解','边界被越过'],'relationship-feeling');if(this.awaiting==='work-source'&&/(事情|任务|太多|做不完)/.test(s))return this.finish('把任务分成今天必须完成、可协商延期、可以直接放弃三类。先列最占脑子的三件，我帮你检查排序依据。','focused','work',['今天必须完成…','可以延期…','先列三件事'],'work-list');if(this.awaiting==='work-source'&&/(人|领导|同事|客户|沟通)/.test(s))return this.finish('问题可能不在工作量本身。把对方的具体要求、你能提供的范围和冲突点各写一句，我们再判断该澄清、拒绝，还是重谈期限。','focused','work',['对方要求…','我的边界是…','帮我组织一句话'],'work-boundary');if(this.awaiting==='cause-or-next'&&/(下一步|怎么办|建议|解决)/.test(s))return this.finish('先选一个二十四小时内能验证的小动作。它要足够具体，也要允许失败后获得信息。你现在想到的两个候选动作是什么？','focused',this.topic,['第一个办法是…','另一个办法是…','帮我评估风险'],'action-options');if(this.awaiting==='cause-or-next'&&/(经过|原因|为什么|发生)/.test(s))return this.finish('从转折点开始讲：在那之前你以为事情会怎样，后来出现了什么新信息？这两句通常比完整时间线更有用。','listening',this.topic,['我原本以为…','后来发现…','转折点是…'],'cause-detail');return null}
 reply(raw,scene='classroom',mode='chat'){const s=raw.trim();this.begin(s);if(mode==='study')return this.study(s);const follow=this.followUp(s);if(follow)return follow;
  const named=s.match(/^(?:我叫|叫我|你可以叫我)([\p{L}\p{N}·]{1,12})[。！!，,]?$/u);if(named){this.name=named[1];return this.finish(`好，${this.name}。我记住了。称呼这种事比看起来重要，叫对了，距离才不会乱。`,'warm','name',['你记得我叫什么吗','那我怎么称呼你','聊聊今天'])}if(/我叫什么|记得我的名字/.test(s))return this.finish(this.name?`记得，${this.name}。你突然检查我，大概已经预想过我答错时要怎么笑了。`:'你还没告诉我。希望我怎么称呼你？','playful','name',['我叫…','叫我同桌就好']);
  const like=s.match(/我(?:很|最|比较)?喜欢(.{1,30})/);if(like){this.remember('likes',like[1]);return this.finish(`记下了。比起“喜欢${this.memory.likes[0]}”这个结论，我更好奇它满足了你什么：审美、习惯，还是某段记忆？`,'warm','preference',[`说说喜欢${this.memory.likes[0]}的原因`,'它和一段回忆有关','只是很合口味'],'preference-why')}const dislike=s.match(/我(?:很|最|比较)?不喜欢(.{1,30})/);if(dislike){this.remember('dislikes',dislike[1]);return this.finish(`好，${this.memory.dislikes[0]}先绕开。要是避不开，我们可以再区分：你排斥的是它本身、发生方式，还是别人要求你的态度。`,'quiet','preference',['它本身','发生方式','别人强迫我'],'dislike-why')}const plan=s.match(/我(?:等会|待会|今天|明天|周末)?(?:要|得|准备)(.{2,30})/);if(plan){this.remember('plans',plan[1]);return this.finish(`要${this.memory.plans[0]}。先别做一张漂亮计划表：说出第一个可以在十分钟内完成、并且能留下痕迹的动作。`,'focused','plan',['第一步是…','帮我拆成三步','我其实在拖延'],'plan-first')}
  if(/别.*(?:捉弄|逗)|不要.*(?:开玩笑|捉弄)|认真听|停止|不想开玩笑/.test(s)){this.gentle=true;return this.finish('好，我停下。你按自己的节奏讲，我先听完整。','quiet','serious',['我想认真说件事','先听经过','现在只想安静'])}if(/可以.*(?:捉弄|开玩笑)|继续逗我/.test(s)){this.gentle=false;return this.finish('收到。那我只捉你话里的小破绽，不拿真正难受的事开玩笑。','playful','tease',['那你试试','来个挑战','先聊今天'])}if(/不想说|不想聊|安静|陪着|静一会/.test(s))return this.finish('好。你不用负责维持对话。雨声、窗风、翻书声，选一个就够了。','quiet','quiet',['听雨声','听窗边的风','等我想说再说']);if(/晚安|睡觉|再见|拜拜|回家了/.test(s))return this.finish(`今天先到这里。${this.memory.plans[0]?`你提过要${this.memory.plans[0]}，明天可以告诉我结果。`:''}路上慢一点。`,'quiet','goodbye',['明天见','再坐一分钟']);
  if(/该不该|怎么选|怎么办|你觉得|建议|纠结|决定/.test(s))return this.finish('我可以一起判断，但先别急着给你一个漂亮结论。你希望我做哪种角色：先听完、帮你列条件，还是直接指出我看到的风险？','focused','decision',['先听完','帮我列条件','直接说风险'],'choice-role');if(/朋友|同学|室友|同事|伴侣|对象|家人|吵架|误会|冷战|关系/.test(s))return this.finish('这类问题先分开两层：实际发生了什么，以及这件事让你怎样理解自己在关系里的位置。你想先讲事实，还是先讲感受？','focused','relationship',['先讲事实','先讲感受','我不知道怎么开口'],'fact-feeling');if(/孤独|孤单|没人陪|一个人/.test(s))return this.finish(this.pick('lonely',['孤独有时来自没有人，有时来自身边有人却说不到真正想说的地方。你现在更接近哪一种？','先不用概括整段生活，只说今天哪个时刻让这种感觉最明显。']),'quiet','lonely',['身边没人','有人但说不到一起','今天有一个瞬间'],'cause-or-next');if(/难过|伤心|委屈|烦|压力|焦虑|不开心|崩溃|失望/.test(s))return this.finish(this.pick('distress',['我先收起玩笑。你现在更需要把经过讲清楚，还是一起决定下一步？','先判断一件事：眼下最重的是事情本身、别人对你的态度，还是你对自己的评价？']),'quiet','distress',['先讲经过','一起想下一步','现在不想分析'],'cause-or-next');if(/累|困|没精神|撑不住|倦|疲惫/.test(s)&&!/上班|工作|加班|开会|领导|老板|客户|职业|辞职/.test(s))return this.finish('先区分身体疲劳和心理耗竭。前者需要停下来补充，后者常常需要减少选择、结束一件悬而未决的事。你更像哪一种？','quiet','tired',['身体真的很累','脑子停不下来','两种都有'],'tired-kind');
  if(/上班|工作|加班|开会|领导|老板|客户|职业|辞职/.test(s))return this.finish('工作让人累，可能是事情太多，也可能是人际边界一直被侵入。哪一类更接近？我会按不同方向继续问。','focused','work',['事情太多','主要是人','我在考虑离开'],'work-source');if(/考试|成绩|分数|考砸|排名|面试|考研|考公/.test(s))return this.finish('先把结果、能力和自我评价分开。结果能复盘，能力能训练，自我评价不该由一次结果直接决定。你现在最需要处理的是哪一层？','focused','exam',['复盘结果','安排训练','情绪过不去'],'exam-layer');if(/钱|工资|存款|买房|房贷|消费|投资|负债/.test(s))return this.finish('钱的问题容易把价值判断和数字混在一起。先列出必须满足的现金约束、时间范围和你最担心的损失，再谈选择。','focused','finance',['现金约束','时间范围','最担心的损失'],'finance-detail');
  if(/食堂|午餐|晚饭|吃饭|吃什么|饿|奶茶|外卖/.test(s))return this.finish(scene==='cafeteria'?'你看菜单的时间比吃饭还认真。今天是想满足口味、控制预算，还是省下排队时间？':'别让空腹替你做决定。今天更在意热乎、清爽，还是方便？','playful','food',['口味优先','预算优先','省时间']);if(/下雨|雨伞|淋雨|天气|降温|刮风/.test(s))return this.finish(scene==='rain'?'雨一时半会儿不会停。我们可以等、一起走，或者把这段时间拿来讲件平时没空讲的事。':'要不要切到雨天走廊？那里的节奏会慢一点。','warm','weather',['一起等雨','现在就走','讲件别的事']);if(/音乐|歌单|耳机|听歌|电影|电视剧|番剧|小说|漫画|游戏/.test(s))return this.finish('你在意的大概不只是作品名。选一个切口吧：它的完成度、某个角色，或它碰到你的那部分。','warm','culture',['聊完成度','聊一个角色','聊它为什么打动我'],'culture-angle');if(/原作|剧情|第.*集|结局|西片/.test(s))return this.finish('原作信息我只谈已经核对的设定和公开资料，具体台词不凭印象补。你想聊人物关系、叙事节奏，还是某个已经说清楚的情节？','listening','canon',['人物关系','叙事节奏','打开原作词条']);
  if(/^(嗯+|好[的呀吧]?|是的|对|可以|行|不知道)[。！!，,]*$/.test(s))return this.finish(this.awaiting?'刚才的问题可以先放着。换个更小的入口：这一刻你最想让我停止问、继续听，还是帮你整理？':'那我把问题缩小一点：今天有没有一件事，你回想时还会停顿一下？','listening',this.topic,['停止问','继续听','帮我整理'],'choice-role');const detail=this.keyDetail(s),question=/[？?]|为什么|怎么|如何|是否/.test(s);if(s.length>=34)return this.finish(`我先抓住一个转折点：“${detail}”。这里同时有事实和你的判断。接下来可以核对判断依据，也可以先看它对你造成了什么影响。`,'listening','detail',['核对判断依据','先说它的影响','我补充前因'],'cause-or-next');if(question)return this.finish('这个问题缺的可能是判断标准。你会用什么结果来证明一个选择值得？先说一个最重要的标准。','focused','open',['我最在意…','两个选项是…','先帮我找标准'],'decision-detail');const context=this.profile.context?.trim(),need=this.profile.needs?.[0];return this.finish(this.pick('fallback',['信息还不足以替你下结论。你想补充背景、说自己的判断，还是让我先问一个具体问题？',context?`你设置的近况是“${context.slice(0,24)}”。这件事与它直接相关，还是今天新发生的？`:'先选一个方向：这件事主要牵涉某个人、一项任务，还是你自己的状态？',need?`你之前选择了“${need}”。这一轮希望我继续倾听、一起分析，还是给一个可执行的小步骤？`:'告诉我你说这句话时，最希望对方理解的是什么。']),'listening','open',['补充背景','说我的判断','问一个具体问题'],'choice-role')}
}
globalThis.CompanionDialogue=CompanionDialogue;
