const $=selector=>document.querySelector(selector);
const scenes={
 classroom:{name:'放学教室',chapter:'CHAPTER 01',phrase:'きょうも、おつかれさま。',time:'☀ 晴天 · 放学后',image:'./assets/takagi.webp',alt:'晴天下午，窗边的高木同学托着脸颊微笑',caption:'今天，也坐在你旁边。',title:'放学后的座位',description:'最后一节课结束，她还没有离开座位，仿佛等着听你开口。',intro:'窗外的风吹过来，她转头看向你。',welcome:'你来啦。今天旁边的座位，也给你留着哦。',suggestions:['今天有点累','打个赌？','别捉弄我啦','说说西片'],hint:'放学前的一点互动。',actions:[['wave','♧','招招手'],['note','✉','传纸条'],['bet','◇','打个赌'],['stay','♡','安静陪伴']]},
 cafeteria:{name:'食堂午后',chapter:'CHAPTER 02',phrase:'ゆっくり、いこう。',time:'☀ 午休 · 食堂',image:'./assets/cafeteria.webp',alt:'高木同学坐在食堂的桌子对面',caption:'今天吃什么？让我猜猜。',title:'食堂的另一边',description:'你端着餐盘坐下来，她看了一眼你的选择，已经想好了一个小问题。',intro:'午后的食堂有点吵，她把餐盘往旁边挪了一点。',welcome:'坐这里吧。你选这道菜，是因为喜欢，还是因为排队最短？',suggestions:['猜猜我点了什么','交换一道菜？','食堂今天人好多','要不要喝奶茶'],hint:'一起决定午餐。',actions:[['share','◒','交换一道菜'],['guess','?','猜午餐'],['tea','☕','递杯茶'],['stay','♡','安静陪伴']]},
 study:{name:'晚自习',chapter:'CHAPTER 03',phrase:'あせらなくていいよ。',time:'☾ 夜色 · 晚自习',image:'./assets/study.webp',alt:'夜晚的教室里，高木同学坐在窗边的书桌旁',caption:'先写完这一题，好吗？',title:'灯亮着的教室',description:'窗外天色渐暗，练习册翻到新的一页。她放低声音，不打扰别人。',intro:'教室渐渐安静下来，她把笔放在练习册边。',welcome:'这题做完再聊。我可以等你。你卡在哪一步？',suggestions:['月考有点紧张','这题我不会','陪我专心十分钟','今天想早点回家'],hint:'把时间留给一件小事。',actions:[['timer','◷','专心十分钟'],['question','✎','一起看题'],['note','✉','传纸条'],['stay','♡','安静陪伴']]},
 rain:{name:'雨天走廊',chapter:'CHAPTER 04',phrase:'雨の日も、悪くないね。',time:'☂ 小雨 · 放学铃后',image:'./assets/rain-corridor.webp',alt:'雨天放学后的教学楼走廊，高木同学拿着透明雨伞回头微笑',caption:'只有一把伞的话，就走近一点。',title:'走廊外的雨声',description:'雨落在栏杆和车棚上，她把伞柄轻轻转向你，等你决定要不要一起走。',intro:'放学铃已经停了，走廊外的雨还没有停。',welcome:'你果然没带伞。是忘了，还是故意等我发现？',suggestions:['我真的忘带伞了','一起等雨小一点','今天降温了','听一会儿雨声'],hint:'在雨停以前慢一点。',actions:[['umbrella','☂','接过伞'],['rain','♩','听雨声'],['walk','↗','一起走'],['stay','♡','靠栏杆等']]},
 valentine:{name:'2月14日',chapter:'CHAPTER 05',phrase:'今日は、何の日だっけ？',time:'♡ 2月14日 · 放学前',image:'./assets/takagi.webp',alt:'二月放学前的窗边教室，高木同学托着脸颊微笑',caption:'今天是什么日子，你不会忘了吧？',title:'藏在纸袋里的心思',description:'教室里有人小声交换巧克力。她把一个纸袋放在桌角，却先问你今天有没有在等什么。',intro:'二月的光落在桌面上，纸袋的提绳轻轻晃了一下。',welcome:'你刚才是不是看了这个纸袋好几次？先猜猜，里面是什么。',suggestions:['我没有偷看','是巧克力吗','你在等我的反应？','情人节在日本怎么过'],hint:'从纸袋、猜测和没有说出口的话开始。',actions:[['chocolate','▣','猜纸袋'],['note','✉','写一句话'],['bet','◇','表情挑战'],['stay','♡','等放学铃']]},
 whiteDay:{name:'3月14日',chapter:'CHAPTER 06',phrase:'覚えていてくれたんだ。',time:'○ 3月14日 · 归途',image:'./assets/study.webp',alt:'三月傍晚的教室里，高木同学坐在窗边',caption:'记得这件事，本身就算一种回答。',title:'一个月后的回礼',description:'三月的风还带着一点凉意。她没有先问礼物贵不贵，只想知道你为什么挑了它。',intro:'放学后的桌面很安静，你把准备好的小礼物往前推了一点。',welcome:'所以，你真的记到今天了。那我先问理由，还是先猜里面是什么？',suggestions:['先猜猜看','我挑了很久','回礼一定要等价吗','白色情人节是什么'],hint:'从回礼的理由聊到记得与回应。',actions:[['gift','◇','递出回礼'],['reason','?','让她猜理由'],['walk','↗','一起回家'],['stay','♡','慢一点说']]},
 festival:{name:'夏日祭',chapter:'CHAPTER 07',phrase:'花火、もうすぐ始まるよ。',time:'✦ 夏夜 · 烟花前',image:'./assets/user-gallery-202609/b1-01.webp',alt:'夏日祭夜晚，高木与西片走在灯火映亮的石阶上',caption:'烟花开始前，先别走散。',title:'人群与第一束烟花',description:'摊位的灯一盏盏亮起，远处传来试放的声响。她在人群边回头，确认你还跟得上。',intro:'风里有团扇、苹果糖和晚夏的气味，第一束烟花还没有升空。',welcome:'人这么多，你还东张西望。要是走散了，你准备怎么找到我？',suggestions:['去捞金鱼吗','我不会走散的','等第一束烟花','夏日祭有哪些摊位'],hint:'先选摊位，再一起等烟花。',actions:[['stall','◎','逛摊位'],['fireworks','✦','等烟花'],['find','⌁','走散挑战'],['walk','↗','并肩往前']]}
};
const terms=[
 {title:'高木与西片',tag:'原作背景',scene:'classroom',summary:'相邻座位与不断往返的捉弄，是原作的关系起点。',detail:'动画官方人物介绍称高木常捉弄邻座的西片，西片想捉弄回去却总被反将一军。本网站里你是新的互动对象，西片仍属于原作背景。'},
 {title:'捉弄',tag:'人物语气',scene:'classroom',summary:'一个观察细节的小玩笑，留给对方回应的空间。',detail:'这里的玩笑只围绕对方的话、表情和日常选择。用户说“别捉弄”后，角色会停下来认真倾听。'},
 {title:'反击挑战',tag:'原创互动',scene:'classroom',summary:'试着打一个小赌，看看谁先露出笑意。',detail:'挑战是本网站原创互动形式，借鉴原作中互相捉弄的节奏，不复现动画中的具体台词或桥段。'},
 {title:'窗边座位',tag:'场景设定',scene:'classroom',summary:'放学后仍在旁边的座位，是对话的开场。',detail:'窗边教室是一种同人演绎。你可以从招手、纸条或一句话开始，不必先完成任务。'},
 {title:'小纸条',tag:'原创互动',scene:'classroom',summary:'一张折好的纸条，可能藏着提问。',detail:'教室与晚自习场景都能传纸条。这里的内容由网站预设，属于中国校园语境下的原创情景。'},
 {title:'月考',tag:'中国校园',scene:'study',summary:'考试前的担心，也可以慢慢讲清楚。',detail:'月考是中国校园情景词条。角色会先回应焦虑或具体困难，再引导你说出卡住的地方。'},
 {title:'晚自习',tag:'中国校园',scene:'study',summary:'说话轻一点，先陪你做完一道题。',detail:'晚自习不是原作设定。本场景强调专心与安静陪伴，十分钟计时器仅在当前页面运行。'},
 {title:'食堂排队',tag:'中国校园',scene:'cafeteria',summary:'今天的队伍和午餐，总有一项值得猜。',detail:'这是原创情景。食堂里的打趣围绕午餐选择，不把中国食堂写成原作剧情。'},
 {title:'交换一道菜',tag:'原创互动',scene:'cafeteria',summary:'她先问你的意见，再决定要不要交换。',detail:'点击互动会出现一段预设回应。这里没有商品购买或真实餐品信息。'},
 {title:'奶茶',tag:'中国日常',scene:'cafeteria',summary:'食堂聊完，还能说说想喝什么。',detail:'奶茶只作为轻松话题。情景回复不会声称角色真的为你购买饮品。'},
 {title:'放学路',tag:'原创情景',scene:'classroom',summary:'一段短路，能把没说完的事说完。',detail:'网站的放学路仅通过对话想象，没有单独的地图或原作地点再现。'},
 {title:'认真倾听',tag:'互动约定',scene:'study',summary:'当你疲惫或要求停止玩笑，她会收起调侃。',detail:'本地情景回复优先识别疲惫、难过与拒绝。它只能进行有限匹配，不能承担心理咨询。'},
 {title:'米娜、由加里、早苗',tag:'原作背景',scene:'classroom',summary:'三位同学有活泼、认真与冷静的不同性格。',detail:'第一季官方人物页介绍米娜常带笑且爱吃，由加里是认真的班长，早苗是冷静的吐槽角色，也有运动的一面。这里暂时不把她们写成可聊天角色。',source:'https://takagi3.me/1st/character/'},
 {title:'河边的水切挑战',tag:'原作背景',scene:'classroom',summary:'西片希望在河边水切赢过高木。',detail:'第二季官方新闻介绍了放学后河边的水切挑战，以及高木似乎看穿西片想法的预告。本网站的“打个赌”只借鉴这种轻松较量感。',source:'https://takagi3.me/2nd/news/20190601_01.php'},
 {title:'第三季的距离',tag:'原作背景',scene:'study',summary:'第三季官方简介强调两人关系随季节变化。',detail:'第三季官方简介延续“捉弄与反击”的关系，也提示随着季节转换，两人的距离与心绪在变化。这是概括性作品信息，不等于本站逐集剧情梳理。',source:'https://takagi3.me/3rd/index.html'},
 {title:'文化祭',tag:'原作背景',scene:'classroom',summary:'第三季第六话的官方主题之一。',detail:'第三季官方分集目录把“文化祭”列为第六话的主题。本站没有重现该话剧情，也未将中国校园活动等同于原作事件。',source:'https://takagi3.me/3rd/episodes/'},
 {title:'二月与三月',tag:'原作背景',scene:'study',summary:'第三季末段的日期主题。',detail:'官方分集目录将第三季第十一话标为“2月14日”，第十二话标为“3月14日”。这里只记录主题信息，避免编造具体场面和台词。',source:'https://takagi3.me/3rd/episodes/'},
 {title:'2月14日',tag:'原作背景',scene:'valentine',summary:'第三季第十一话以这个日期为标题。',detail:'动画第三季官方分集页将第十一话标为“2月14日”。本站据此设计纸袋、猜测与放学前的原创互动，不复现该话画面和台词。',source:'https://takagi3.me/3rd/episodes/ep11.html'},
 {title:'情人节的表达',tag:'原创互动',scene:'valentine',summary:'礼物之外，也可以聊期待、犹豫和对方的反应。',detail:'互动会先询问你在意的是礼物、回应还是关系本身，再顺着一个具体细节继续。它属于本站原创情境。'},
 {title:'3月14日',tag:'原作背景',scene:'whiteDay',summary:'第三季第十二话以这个日期为标题。',detail:'动画第三季官方分集页将第十二话标为“3月14日”。本站把它处理为“记得、选择和回应”的原创章节，不声称还原原作剧情。',source:'https://takagi3.me/3rd/episodes/ep12.html'},
 {title:'白色情人节的回礼',tag:'生活文化',scene:'whiteDay',summary:'回礼可以成为说明心意和边界的契机。',detail:'本站不会把礼物价格当作关系答案。对话会继续询问选择理由、对方偏好和彼此是否舒服。'},
 {title:'第二季夏日祭',tag:'原作背景',scene:'festival',summary:'第二季第十二话的官方标题是“夏祭り”。',detail:'第二季官方故事页确认第十二话标题为“夏祭り”。第三季官方新闻也把它称为第二季最终话的重要节点。本站只借鉴夏夜、人群与等待烟花的氛围。',source:'https://takagi3.me/2nd/story/story12.php'},
 {title:'烟花开始以前',tag:'原创互动',scene:'festival',summary:'经典感往往来自等待、寻找和没有急着说完的话。',detail:'摊位、走散挑战和烟花倒数由本站重新编排。你可以从想逛的摊位、怕不怕走散或想和谁看烟花继续聊。'},
 {title:'观察后的玩笑',tag:'人物语气',scene:'classroom',summary:'先注意到细节，再用一个小问题让对方露出反应。',detail:'小学馆的作品介绍认为，这类捉弄不构成恶意的重要原因，是高木熟悉西片并掌握恰当距离。本站据此把玩笑限制在用户刚说的话和可退出的小挑战中。',source:'https://www.shogakukan.co.jp/news/142170'},
 {title:'快速来回的对话',tag:'人物语气',scene:'classroom',summary:'像乒乓球般来回，同时保留停顿和观察。',detail:'高桥李依在访谈中转述，配音现场既像下棋般思考，也像乒乓球般迅速往返。本站将它转化为“回应细节、轻推一步、把话题交还给你”的三段节奏。',source:'https://s.animeanime.jp/article/2022/06/09/70042.html'},
 {title:'知道何时停下',tag:'互动约定',scene:'study',summary:'明确拒绝、疲惫或认真话题出现时，玩笑会暂停。',detail:'真实感来自对边界的判断。说“别逗我”“认真听”或表达难过后，角色会改用短句、具体问题和安静陪伴。'},
 {title:'这台设备会记住什么',tag:'互动约定',scene:'classroom',summary:'偏好保存在当前浏览器，对话记录在刷新后清空。',detail:'称呼、身份、回应偏好、首选 Chapter、场景、动态、小游戏与音乐设置会保存在当前浏览器。换设备、无痕窗口或清理浏览器数据后不会同步。AI 在线时，本轮消息、近期对话、个性设置以及你主动附上的聊天图片会发送给所选模型生成回复；聊天图片不会写入长期记忆，API 密钥只保存在站点服务端。'},
 {title:'透明雨伞',tag:'原创情景',scene:'rain',summary:'雨天走廊里，一把伞形成新的小挑战。',detail:'这是面向中国校园日常创作的场景。角色会围绕忘带伞、降温、车棚和放学路互动，不声称属于原作剧情。'},
 {title:'值日结束',tag:'中国校园',scene:'rain',summary:'走廊变安静后，才发现雨还没停。',detail:'值日、教学楼走廊和自行车棚属于本站的中国校园语境。它们用来承接真实日常，不替代原作地点。'},
 {title:'二十卷完结',tag:'原作背景',scene:'classroom',summary:'小学馆电子书页面标注原作单行本全二十卷完结。',detail:'本站只把这一事实作为作品范围说明，不搬运漫画画面，也不生成逐话台词。',source:'https://e-comi.shogakukan.co.jp/books/091250150000d0000000'},
 {title:'先观察再开口',tag:'人物语气',scene:'classroom',summary:'她会先抓住一句话里的小细节，再提出问题。',detail:'对话尽量回应你刚提到的对象、情绪或动作，再用轻微的反问延续话题。没有识别到细节时，会直接请你补充，而不会假装已经理解。'},
 {title:'称呼与距离',tag:'互动约定',scene:'classroom',summary:'称呼由你决定，也可以随时重新设置。',detail:'“同桌”只是默认称呼。个性设置中的称呼优先于名字，并会用于章节开场和部分回应。设置保存在当前浏览器。'},
 {title:'夏日窗风',tag:'原创情景',scene:'classroom',summary:'窗帘、蝉声与放学后的光，构成更轻盈的夏日氛围。',detail:'精选图库中的夏日窗边为本站原创插画。背景音乐使用程序实时生成的疏朗音符，每次播放会有细微变化。'},
 {title:'食堂里的选择题',tag:'中国校园',scene:'cafeteria',summary:'从排队、菜品和座位开始一次轻松对话。',detail:'食堂情境会用二选一或猜测推动对话。点击交换菜品只生成情境反馈，不代表真实购买、赠送或交易。'},
 {title:'留一点停顿',tag:'人物语气',scene:'study',summary:'认真话题出现时，回复会变短，给你继续说的空间。',detail:'表达疲惫、难过或“先听我说”后，角色会减少调侃，先确认你希望倾听、拆解问题还是安静陪伴。'},
 {title:'题目提示的边界',tag:'互动约定',scene:'study',summary:'先整理条件，再给下一步提示。',detail:'学习陪伴适合简单计算、一元一次方程和题目条件梳理。复杂题目只提供有限的拆解，不能保证完整解答正确。'},
 {title:'夜灯自习',tag:'原创情景',scene:'study',summary:'暖色台灯与窗外夜色，让专注不显得紧绷。',detail:'夜灯自习精选图为本站原创插画。人物动态可以选择轻柔呼吸、夏风轻摆、偶尔回眸或静态画面。'},
 {title:'雨滴的疏密',tag:'原创情景',scene:'rain',summary:'雨声不会以完全相同的节拍重复。',detail:'“屋檐雨滴”由浏览器实时生成大小、间隔不同的雨滴声，并穿插很轻的和弦。它不会录音，也不会读取麦克风。'},
 {title:'共伞的分寸',tag:'互动约定',scene:'rain',summary:'靠近是一段可退出的情境，不替你作决定。',detail:'接伞、等雨和一起走都只生成文字情境。你可以切换章节、进入安静陪伴或直接开始新的话题。'},
 {title:'本地图库',tag:'互动约定',scene:'rain',summary:'精选图随网站提供，自选背景图只留在你的设备。',detail:'站内精选图可以直接切换。作为背景选择的本地图片不会上传；只有你在聊天框明确附上的图片，才会压缩后随当前消息发送给所选视觉模型，也不会出现在朋友打开的网页中。'},
 {title:'和食与地域',tag:'中日饮食',scene:'cafeteria',summary:'气候、物产和年中仪式形成日本各地不同的饮食习惯。',detail:'日本农林水产省的地域料理资料强调，和食会随地区、气候和家庭传统变化。以杂煮为例，汤底、调味、年糕形状与配料都可能不同，因此聊天会先询问具体地区。',source:'https://www.maff.go.jp/e/policies/market/divers.html'},
 {title:'中国茶与待客',tag:'中日饮食',scene:'cafeteria',summary:'茶既是饮品，也参与家庭、邻里与待客交往。',detail:'联合国教科文组织记录，中国传统制茶技艺及其社会实践覆盖多类茶叶和多种地域习惯。页面会把茶作为生活文化话题，同时避免用单一饮法代表所有地区。',source:'https://ich.unesco.org/en/RL/traditional-tea-processing-techniques-and-associated-social-practices-in-china-01884'},
 {title:'餐桌先问条件',tag:'中日饮食',scene:'cafeteria',summary:'预算、忌口、过敏与时间，比文化标签更能决定一顿饭。',detail:'聊天提出饮食建议前会优先结合所在地、预算、忌口和当天安排。中日文化资料用于补充背景，不会根据国籍推断个人口味。'},
 {title:'睡眠休养感',tag:'作息文化',scene:'study',summary:'睡多久和醒来是否恢复，都值得一起观察。',detail:'日本厚生劳动省睡眠指南按年龄阶段提供建议，并强调规律、环境和睡眠休养感。成年人至少约六小时可作为一般参考，持续失眠或白天功能受损仍需专业评估。',source:'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/kenkou/suimin/index.html'},
 {title:'作息不按国籍猜',tag:'作息文化',scene:'study',summary:'学校、行业、通勤和家庭责任会改变每天的节奏。',detail:'页面会结合你填写的身份、所在地、当前情境和需求讨论作息，不会把“中国人”或“日本人”当作固定时间表。'},
 {title:'日本南北气候',tag:'天气气候',scene:'rain',summary:'从北部亚寒带到南部亚热带，天气经验差异很大。',detail:'日本气象厅指出，日本南北气候跨度明显，太平洋侧和日本海侧的冬季表现也不同。长期气候只能提供背景，当天安排仍应查询实时预报。',source:'https://www.data.jma.go.jp/cpd/longfcst/en/tourist.html'},
 {title:'中国季风与地形',tag:'天气气候',scene:'rain',summary:'东部季风、西北干旱与高原高寒构成明显区域差异。',detail:'中国气候受到纬度、海陆位置和三级地势等多重因素影响。同一省份也可能因海拔和局地环境出现差异，因此天气对话会询问具体城市和日期。',source:'https://www.mee.gov.cn/zcwj/gwywj/201811/t20181129_676510.shtml'},
 {title:'气候不等于预报',tag:'天气气候',scene:'rain',summary:'季节规律可以解释背景，不能代替今天的实时天气。',detail:'页面没有实时气象工具时，会依据你提供的天气继续聊天，并提示查询当地气象部门，不会编造温度、降雨概率或预警。'},
 {title:'日本列岛与地方生活',tag:'地理常识',scene:'classroom',summary:'南北延伸、山地众多，地形连接着交通、气候与地方料理。',detail:'日本国土地理院资料显示，日本地形以山地和丘陵为主。讨论地区差异时会落到具体自然区与城市，避免把关东、关西等称呼当作人格分类。',source:'https://www.gsi.go.jp/atlas/archive/j-atlas-d_2e_02.pdf'},
 {title:'中国三级地势',tag:'地理常识',scene:'classroom',summary:'整体西高东低，山地、高原、盆地、平原和丘陵并存。',detail:'复杂地形与季风共同塑造交通、物产和生活方式。页面会把“南方”“北方”继续细分到城市或自然区，再讨论实际差异。',source:'https://www.locpg.gov.cn/zggq/2014-01/04/c_125956300.htm'},
 {title:'中日比较的边界',tag:'地理常识',scene:'classroom',summary:'先看地区、代际和家庭，再谈公共文化差异。',detail:'聊天进行中日比较时会区分可核对的公共事实与个人经验，不把文化倾向写成每个人都遵守的规则。'},
 {title:'下班后的十分钟',tag:'成年日常',scene:'classroom',summary:'先把一天放在门外，再决定要复盘还是休息。',detail:'可以从今天最耗神的一刻、意外顺利的一件事，或回家后最先做的动作开始。角色会先确认你想复盘、解决问题，还是轻松说几句。'},
 {title:'周末留白',tag:'成年日常',scene:'cafeteria',summary:'空出来的时间，也可能让人一时不知道做什么。',detail:'不急着列完整计划。先在恢复精力、见人、独处和完成一件小事之间选一个方向，再安排最低成本的一步。'},
 {title:'今天还算顺利的事',tag:'成年日常',scene:'classroom',summary:'从一件没有出错的小事，重新看见今天。',detail:'这里不会要求你强行积极。可以只找一个客观上顺利、节省时间或少消耗了一点精力的瞬间。'},
 {title:'被误解以后',tag:'关系与边界',scene:'rain',summary:'先把发生的事、自己的解释和感受分开。',detail:'把对方具体说过的话、你当时的反应和你最在意的部分分别讲清楚，再决定澄清、等待或保持距离。'},
 {title:'一句说不出口的拒绝',tag:'关系与边界',scene:'study',summary:'拒绝可以短、清楚，并给出真实边界。',detail:'你可以提供对方的要求、自己能做到的范围和最担心的后果。角色会协助整理一句可直接使用的话。'},
 {title:'两难选择',tag:'选择与计划',scene:'classroom',summary:'先看想保住什么，再比较每个选项的代价。',detail:'适合处理工作、学习和关系里的现实选择。页面会询问不可接受的结果、可逆程度和最近可验证的一步。'},
 {title:'拖延的第一步',tag:'选择与计划',scene:'study',summary:'把任务缩到十分钟内能留下痕迹的动作。',detail:'不从宏大计划开始。先写一个标题、打开材料、列三项条件或完成一道题，让行动产生可见结果。'},
 {title:'一首歌留下的画面',tag:'兴趣与作品',scene:'rain',summary:'歌曲被记住，常常和一个场景或阶段连在一起。',detail:'可以从第一次听见、最喜欢的声音层次、联想到的画面或当时正在经历的生活展开。无需引用歌词。'},
 {title:'重看一部作品',tag:'兴趣与作品',scene:'classroom',summary:'第二次注意到的东西，往往和第一次不同。',detail:'聊作品时会继续问你先记住人物、关系、画面还是节奏，并把变化连接到你现在的观看经验。'},
 {title:'夏夜的声音',tag:'季节与生活',scene:'classroom',summary:'风、蝉声、远处的车和晚归的人构成夏夜。',detail:'季节话题会先落到你所在地的真实温度、光线和声音，再连接饮食、衣着或个人记忆。'},
 {title:'心情说不清的时候',tag:'情绪整理',scene:'rain',summary:'不用先找到准确的情绪名称。',detail:'可以先描述身体感觉、脑中反复出现的句子和最想避开的事情，再决定是否继续分析。'},
 {title:'复盘一次卡住',tag:'学习与复盘',scene:'study',summary:'区分知识缺口、执行失误和时间分配。',detail:'把目标、已经做过的步骤和最不确定的一处写出来。角色会先检查条件和推理，再决定提示或解释。'},
 {title:'放课后的图书室',tag:'日本青春',scene:'classroom',summary:'借书卡、夕光和一张夹在书里的便笺。',detail:'这是原创青春情境。图书室快要闭馆，你们各自挑了一本书。她发现你在同一页停了很久，于是问你记住的是一句话，还是读到那句话时的自己。'},
 {title:'部活结束后的汽水',tag:'日本青春',scene:'cafeteria',summary:'自动贩卖机亮起时，夏日训练刚好结束。',detail:'这是原创青春情境。你们在自动贩卖机前各选一瓶汽水，从口味、社团活动和今天最累的一刻继续聊。'},
 {title:'写在便笺上的短歌',tag:'日本青春',scene:'study',summary:'用五行短句留住今天一个很小的画面。',detail:'这是原创文字游戏。可以借用短歌五七五七七的节奏观察日常，也可以只写五行中文短句，不要求严格押韵。她会先问你想留下光线、声音、动作还是一句没说完的话。'},
 {title:'车站屋檐下的雨宿り',tag:'日本青春',scene:'rain',summary:'列车还没来，雨把谈话留在屋檐下面。',detail:'“雨宿り”指避雨。这是原创通学情境。她会从鞋边的水迹、车站广播或错过的一班车中挑一个细节，把话题接到你今天正在等待的事。'},
 {title:'鞋柜里的小纸袋',tag:'日本青春',scene:'valentine',summary:'先猜纸袋里装了什么，再谈为什么一直没有拿出来。',detail:'这是原创情境。重点放在等待、犹豫和对方是否舒服。可以聊礼物，也可以聊一句没有及时说出口的话。'},
 {title:'三月回信',tag:'日本青春',scene:'whiteDay',summary:'一个月后的回答，先从“我还记得”开始。',detail:'这是原创情境。她会问你真正想回应的是礼物、心意，还是那段等待。回答可以很短，也可以从挑选回礼的过程展开。'},
 {title:'花火结束后的归途',tag:'日本青春',scene:'festival',summary:'烟花散去以后，人群和脚步声慢慢远了。',detail:'这是原创夏夜情境。她会抓住你在烟花结束后最先注意到的声音、颜色或动作，再把未说完的话留到回程。'}
];
let activeScene='classroom',activeTerm=null,localTopicTurns=0,aiMode='chat',busy=false,turn=0,serious=false,challenge=0,focusTimer=null,focusEnd=0,focusTick=null;const sceneEl=$('#scene'),log=$('#log'),input=$('#input'),send=$('#send');
function save(name,value){try{localStorage.setItem(name,value)}catch{}}
function load(name){try{return localStorage.getItem(name)}catch{return null}}
const profileDefaults={name:'',address:'同桌',identity:'学生',difficulty:'hard',difficultyVersion:3,context:'',location:'',interests:[],needs:['轻松陪伴'],modelPreference:'deepseek-flash',chatStyle:'gentle',currentMood:'calm',startScene:'last',startMode:'last'};
function readProfile(){try{const value=JSON.parse(load('takagi-profile')||'null');if(!value||typeof value!=='object')return{...profileDefaults};const migrated=value.difficultyVersion===3?value:{...value,difficulty:value.difficulty||'hard',difficultyVersion:3};return{...profileDefaults,...migrated,needs:Array.isArray(migrated.needs)?migrated.needs.slice(0,3):profileDefaults.needs}}catch{return{...profileDefaults}}}
let profile=readProfile();
if(String(profile.modelPreference||'').startsWith('gpt-')){profile.modelPreference='deepseek-flash';save('takagi-profile',JSON.stringify(profile))}
const savedMode=load('takagi-chat-mode');aiMode=profile.startMode==='study'?'study':profile.startMode==='chat'?'chat':savedMode==='study'?'study':'chat';
document.querySelectorAll('[data-mode]').forEach(item=>item.setAttribute('aria-pressed',String(item.dataset.mode===aiMode)));
function preferredAddress(){return profile.address?.trim()||profile.name?.trim()||'你'}
function welcomeFor(scene){const line=scene.welcome;return profile.address?.trim()?`${preferredAddress()}，${line}`:line}
if(load('takagi-motion')==='off')sceneEl.classList.remove('alive');if(load('takagi-pose')==='close'){$('#pose').value='close';sceneEl.classList.add('closer')}
function syncMotion(){const on=sceneEl.classList.contains('alive');$('#motion').textContent=on?'Ⅱ':'▷';$('#motion').setAttribute('aria-label',on?'暂停动态':'开启动态');$('#motion').setAttribute('aria-pressed',String(on));$('.scene-controls>span').textContent=on?'轻轻摇晃，等你开口':'动态已暂停'}syncMotion();
$('#motion').onclick=()=>{sceneEl.classList.toggle('alive');syncMotion();save('takagi-motion',sceneEl.classList.contains('alive')?'on':'off')};
function pose(value){if(!['daily','close','portrait','wide'].includes(value))throw Error('无效姿态');$('#pose').value=value;sceneEl.classList.toggle('closer',value==='close');sceneEl.dataset.pose=value;save('takagi-pose',value);return {pose:value}}$('#pose').onchange=e=>pose(e.target.value);
const toneMarks={warm:['☀','暖意'],playful:['✦','小得意'],quiet:['☁','轻声'],focused:['✎','认真'],listening:['◌','在听']};
function assistantHeader(mood='warm'){const meta=textEl('span','','message-meta'),tone=toneMarks[mood]||toneMarks.listening;meta.append(textEl('b','高木'),textEl('i',`${tone[0]} ${tone[1]}`,'tone-sticker'));return meta}
function add(role,text,mood='warm'){const d=document.createElement('div');d.className='message '+role;if(role==='assistant')d.append(assistantHeader(mood));const p=document.createElement('p');p.textContent=text;d.append(p);log.append(d);log.scrollTop=log.scrollHeight;return d}
function attachReactions(row){log.querySelectorAll('.reply-reactions').forEach(item=>item.remove());const bar=textEl('div','','reply-reactions');[['♡','收到'],['☺','被你说中'],['…','安静一下']].forEach(([symbol,label])=>{const b=textEl('button',`${symbol} ${label}`);b.type='button';b.onclick=()=>{bar.querySelectorAll('button').forEach(item=>item.disabled=true);if(symbol==='…'){setQuiet(true);b.textContent='… 就坐一会儿'}else{pulseReaction(symbol==='☺'?'playful':'warm');b.textContent=symbol==='☺'?'☺ 看来猜中了':'♡ 她收到了';if(symbol==='☺')addContext('你轻轻点了点头。')}};bar.append(b)});row.append(bar);log.scrollTop=log.scrollHeight}
function addContext(text){const d=document.createElement('div');d.className='intro';d.textContent='✧ '+text;log.append(d);log.scrollTop=log.scrollHeight}
function renderSuggestions(items){const needPrompt=profile.needs.includes('学习督促')?'陪我开始一项任务':profile.needs.includes('认真倾听')?'今天先听我说':profile.needs.includes('任务规划')?'帮我拆一下今天的安排':'';const defaults=aiMode==='study'?['分析一道方程','检查我的解法','整理已知条件','只提示下一步']:[needPrompt,...scenes[activeScene].suggestions].filter((item,index,array)=>item&&array.indexOf(item)===index);const chips=$('#suggestions');chips.replaceChildren();(items?.length?items:defaults).slice(0,4).forEach(t=>{const b=document.createElement('button');b.textContent=t;b.disabled=busy;b.onclick=()=>submit(t);chips.append(b)})}
function syncChatContext(){const modeName=aiMode==='study'?'结构化学习陪伴':'上下文陪伴';$('#chat-context').textContent=scenes[activeScene].name+' · '+modeName;input.placeholder=aiMode==='study'?'输入题目、已有步骤和最不确定的一处…':'可以直接说复杂一点，我会沿着上一轮继续…'}
function setScene(key){if(!scenes[key])throw Error('无效场景');if(focusTimer){clearInterval(focusTick);focusTimer=null;focusEnd=0;}activeScene=key;sceneEl.dataset.scene=key;const s=scenes[key];$('#chapter').textContent=s.chapter;$('#scene-time').textContent=s.time;$('#scene-caption').textContent=s.caption;$('#scene-title').textContent=s.title;$('#scene-description').textContent=s.description;const phrase=$('#scene-phrase');if(phrase)phrase.textContent=s.phrase||'きょうも、おつかれさま。';syncChatContext();$('#action-hint').textContent=s.hint;$('#character').src=s.image;$('#character').alt=s.alt;document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===key)));renderSuggestions();const actions=$('#actions');actions.replaceChildren();s.actions.forEach(([action,icon,label])=>{const b=document.createElement('button');b.dataset.action=action;const symbol=document.createElement('span');symbol.textContent=icon;b.append(symbol,document.createTextNode(label));b.onclick=()=>interact(action);actions.append(b)});const welcome=welcomeFor(s);speak(welcome,'scene');addContext(s.intro);add('assistant',welcome);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)sceneEl.animate([{opacity:.72,transform:'translateY(3px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:'ease-out'});save('takagi-scene',key);renderTermPreview();if(window.refreshSceneGallery)window.refreshSceneGallery();return {scene:key,name:s.name}}
let reactionTimer;
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{if(b.dataset.scene!==activeScene)setScene(b.dataset.scene)});
const savedScene=load('takagi-scene');const initial=profile.startScene&&profile.startScene!=='last'&&scenes[profile.startScene]?profile.startScene:savedScene&&scenes[savedScene]?savedScene:'classroom';log.replaceChildren();setScene(initial);
function pulseReaction(kind='warm'){const spark=$('#reaction-spark');if(!spark)return;spark.textContent=({playful:'✦',quiet:'…',focused:'⌁',scene:'↗',listening:'· · ·'})[kind]||'♡';spark.dataset.show='true';clearTimeout(spark._timer);spark._timer=setTimeout(()=>spark.dataset.show='false',850)}
function speak(text,kind='warm'){const line=text.match(/^.*?[。？！]/)?.[0]||text;$('#bubble').textContent=line.length>58?line.slice(0,58)+'…':line;sceneEl.dataset.mood=kind==='scene'?'warm':kind;sceneEl.classList.remove('bubble-pop');void sceneEl.offsetWidth;sceneEl.classList.add('bubble-pop','reacting');pulseReaction(kind);clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>sceneEl.classList.remove('reacting','bubble-pop'),900)}
function interact(action){const s=activeScene;let line='';if(action==='wave')line='嗯，我看到你啦。不用挥那么大力，窗户都要替你回应了。';if(action==='note')line=s==='study'?'纸条上写着：先圈出已知条件，再看我。':'纸条上写着：你觉得谁会先忍不住笑？';if(action==='bet'){challenge++;line=challenge%2?'好啊，赌你先笑。现在就开始？':'这次算你赢。看你忍得那么认真，我差点先笑了。'}if(action==='stay')setQuiet(true);if(action==='stay')line=s==='rain'?'好，靠在这里听一会儿。雨不会因为我们着急就停得更快。':s==='study'?'嗯。先安静一会儿，翻页时轻一点。':'好，就这样坐一会儿。你不用负责让气氛一直热闹。';if(action==='share')line='先问问你：愿意用一道菜换我的这道吗？答应得太快，我会怀疑你早就盯上了。';if(action==='guess')line='让我猜，你在两道菜之间犹豫了很久，最后选了排队短的。';if(action==='tea')line='谢谢。你还记得给我也带一杯呀。甜度是不是又按你自己的口味选的？';if(action==='question')line='把题目里最不确定的那一步指给我。我们只拆这一处。';if(action==='umbrella')line='拿稳一点。伞面会往你那边偏，是因为风，不是因为我哦。';if(action==='rain')line='先不说话。听，栏杆上的雨声比车棚那边更轻一点。';if(action==='walk')line='走吧。只有一把伞的话，你可别故意落后半步。';if(action==='timer'){if(focusTimer){clearInterval(focusTick);focusTimer=null;line='十分钟专心时间提前结束。先看看刚才完成了什么。'}else{focusEnd=Date.now()+10*60*1000;focusTimer=true;line='好，十分钟。你先专心，我负责在旁边不打扰你。';focusTick=setInterval(()=>{const left=Math.max(0,Math.ceil((focusEnd-Date.now())/1000));const m=String(Math.floor(left/60)).padStart(2,'0'),sec=String(left%60).padStart(2,'0');const b=$('[data-action="timer"]');if(b)b.lastChild.textContent=left?'专心 '+m+':'+sec:'专心十分钟';if(!left){clearInterval(focusTick);focusTimer=null;add('assistant','十分钟到了。先别评价自己，数一数刚才完成了几步。');speak('十分钟到了，伸个懒腰吧。')}} ,1000)}}if(!line)throw Error('无效互动');speak(line);addContext(({wave:'她抬眼看过来。',note:'一张小纸条停在桌边。',bet:'她笑着接下了挑战。',stay:'你们暂时把话放下。',share:'她看了看你的餐盘。',guess:'她想了一下。',tea:'她轻轻道了谢。',question:'她看向你的练习册。',timer:'专心的时间开始了。',umbrella:'透明伞柄递到你手边。',rain:'你们一起听走廊外的雨。',walk:'她把伞往中间挪了一点。'})[action]);add('assistant',line);return {action,reply:line}}
$('#character-hit').onclick=()=>interact('wave');
const dialogue=new CompanionDialogue();
dialogue.setProfile(profile);
const CHAT_CONTEXT_LIMIT=12;
function readSessionHistory(){try{const value=JSON.parse(sessionStorage.getItem('takagi-chat-session')||'[]');return Array.isArray(value)?value.filter(turn=>turn&&['user','assistant'].includes(turn.role)&&typeof turn.text==='string').slice(-CHAT_CONTEXT_LIMIT):[]}catch{return[]}}
function saveSessionHistory(){try{sessionStorage.setItem('takagi-chat-session',JSON.stringify(aiHistory.slice(-CHAT_CONTEXT_LIMIT)))}catch{}}
function rememberTurn(userText,assistantText){aiHistory.push({role:'user',text:String(userText||'').slice(0,800)},{role:'assistant',text:String(assistantText||'').slice(0,800)});aiHistory.splice(0,Math.max(0,aiHistory.length-CHAT_CONTEXT_LIMIT));saveSessionHistory()}
const aiHistory=readSessionHistory();
if(aiHistory.length)addContext(`已接上本次标签页里的短期对话记忆，共 ${aiHistory.length} 条。关闭标签页后会清除。`);
let pendingImage=null,voiceRecorder=null,voiceStream=null,voiceChunks=[],voiceBase='',voiceState='idle',voiceTimer=null,voiceStartedAt=0,voiceFallback=null,voiceFallbackText='',voiceFallbackError='';
const chatForm=$('#chat-form'),inputBottom=chatForm.querySelector('.input-bottom'),inputHint=inputBottom.querySelector('span');
const passwordInput=$('#ai-password'),passwordStatus=$('#password-status'),forgetPassword=$('#forget-ai-password');
try{passwordInput.value=sessionStorage.getItem('takagi-ai-password')||''}catch{}
if(passwordInput.value)passwordStatus.textContent='已恢复本标签页中验证过的密码。刷新后仍可用，关闭标签页或点击“清除”后失效。';
forgetPassword.hidden=!passwordInput.value;
passwordInput.addEventListener('input',()=>{passwordStatus.textContent='输入后发送一条消息即可校验。密码只保留在当前标签页。';forgetPassword.hidden=!passwordInput.value});
forgetPassword.onclick=()=>{passwordInput.value='';try{sessionStorage.removeItem('takagi-ai-password')}catch{}forgetPassword.hidden=true;passwordStatus.textContent='已清除当前标签页中的 AI 访问密码。';passwordInput.focus()};
const inputActions=document.createElement('div');inputActions.className='input-actions';
const attachButton=textEl('button','＋ 图片','input-tool');attachButton.type='button';attachButton.setAttribute('aria-label','添加聊天图片');
const voiceButton=textEl('button','◉ 开始听','input-tool');voiceButton.type='button';voiceButton.setAttribute('aria-label','开始语音输入');voiceButton.setAttribute('aria-pressed','false');
const voiceStatus=textEl('small','点“开始听”录音，再点“停止并转文字”。文字只会写入本页输入框，确认后再发送。','voice-status');voiceStatus.setAttribute('role','status');voiceStatus.setAttribute('aria-live','polite');voiceStatus.dataset.state='idle';
const imagePicker=document.createElement('input');imagePicker.type='file';imagePicker.accept='image/jpeg,image/png,image/webp,image/gif';imagePicker.hidden=true;
const attachmentPreview=textEl('div','','chat-attachment');attachmentPreview.hidden=true;chatForm.insertBefore(attachmentPreview,input);inputActions.append(attachButton,voiceButton,send);inputBottom.replaceChildren(inputHint,inputActions);chatForm.insertBefore(voiceStatus,inputBottom);chatForm.append(imagePicker);inputHint.textContent='可输入、语音、粘贴或拖入图片';
function syncComposer(){send.disabled=busy||(!input.value.trim()&&!pendingImage);attachButton.disabled=busy;voiceButton.disabled=busy||voiceButton.dataset.supported==='false'||voiceState==='converting'||voiceState==='requesting';inputHint.textContent=`${Math.min(input.value.length,1200)} / 1200 · 可输入、语音、粘贴或拖入图片`}
function clearPendingImage(){pendingImage=null;attachmentPreview.hidden=true;attachmentPreview.replaceChildren();syncComposer()}
function showPendingImage(){attachmentPreview.replaceChildren();if(!pendingImage){attachmentPreview.hidden=true;return}const image=document.createElement('img');image.src=pendingImage.dataUrl;image.alt='待发送图片预览';const info=textEl('span','');info.append(textEl('strong',pendingImage.name),textEl('small','已压缩 · 仅随本轮发送给 DeepSeek'));const remove=textEl('button','移除');remove.type='button';remove.setAttribute('aria-label','移除待发送图片');remove.onclick=clearPendingImage;attachmentPreview.append(image,info,remove);attachmentPreview.hidden=false;syncComposer()}
function loadLocalImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(Error('invalid image'))};image.src=url})}
async function prepareImage(file){
 if(!file||!/^image\/(jpeg|png|webp|gif)$/i.test(file.type)||file.size>8*1024*1024){$('#ai-status').textContent='请选择不超过 8 MB 的 JPG、PNG、WebP 或 GIF 图片。';return}
 attachButton.disabled=true;$('#ai-status').textContent='正在压缩图片…';
 try{const image=await loadLocalImage(file);let dataUrl='';for(const [maxSize,quality] of [[1280,.82],[1080,.72],[900,.62]]){const scale=Math.min(1,maxSize/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);dataUrl=canvas.toDataURL('image/jpeg',quality);if(dataUrl.length<=1850000)break}if(dataUrl.length>1850000)throw Error('too large');pendingImage={name:file.name.slice(0,80),dataUrl};showPendingImage();$('#ai-status').textContent='图片已就绪 · 发送时将使用 DeepSeek Flash 识别';}
 catch{$('#ai-status').textContent='这张图片暂时无法读取，请换一张再试。';clearPendingImage()}finally{attachButton.disabled=busy}
}
attachButton.onclick=()=>imagePicker.click();imagePicker.onchange=()=>{const file=imagePicker.files?.[0];imagePicker.value='';if(file)prepareImage(file)};
chatForm.addEventListener('dragover',event=>{if(Array.from(event.dataTransfer?.types||[]).includes('Files')){event.preventDefault();chatForm.classList.add('drop-active')}});chatForm.addEventListener('dragleave',()=>chatForm.classList.remove('drop-active'));chatForm.addEventListener('drop',event=>{event.preventDefault();chatForm.classList.remove('drop-active');const file=Array.from(event.dataTransfer?.files||[]).find(item=>item.type.startsWith('image/'));if(file)prepareImage(file)});
input.addEventListener('paste',event=>{const file=Array.from(event.clipboardData?.files||[]).find(item=>item.type.startsWith('image/'));if(file){event.preventDefault();prepareImage(file)}});
function paintVoice(state,message){voiceState=state;voiceStatus.dataset.state=state;voiceStatus.textContent=message;voiceButton.setAttribute('aria-pressed',String(state==='listening'));voiceButton.textContent=state==='listening'?'■ 停止并转文字':state==='requesting'?'◌ 等待麦克风…':state==='converting'?'◌ 云端转写中…':state==='unsupported'?'语音暂不可用':'◉ 开始听';voiceButton.setAttribute('aria-label',state==='listening'?'停止录音并转换成文字':state==='unsupported'?'语音转写当前不可用':'开始语音输入');syncComposer()}
function releaseVoiceStream(){if(voiceStream){voiceStream.getTracks().forEach(track=>track.stop());voiceStream=null}window.dispatchEvent(new CustomEvent('takagi:voice-recording',{detail:{active:false}}))}
function startBrowserSpeechFallback(){
 const SpeechInput=window.SpeechRecognition||window.webkitSpeechRecognition;voiceFallbackText='';voiceFallbackError='';if(!SpeechInput)return;
 try{voiceFallback=new SpeechInput();voiceFallback.lang='zh-CN';voiceFallback.interimResults=true;voiceFallback.continuous=true;voiceFallback.onresult=event=>{let words='';for(let i=0;i<event.results.length;i++)words+=event.results[i][0]?.transcript||'';voiceFallbackText=words.trim()};voiceFallback.onerror=event=>{voiceFallbackError=event.error||'unavailable'};voiceFallback.start()}catch{voiceFallback=null}
}
function stopBrowserSpeechFallback(){if(voiceFallback){try{voiceFallback.stop()}catch{}voiceFallback=null}}
async function transcribeVoice(blob){
 const form=new FormData();form.append('audio',blob,blob.type.includes('mp4')?'voice.m4a':blob.type.includes('ogg')?'voice.ogg':'voice.webm');
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),32000);let response;
 try{response=await fetch('/api/transcribe',{method:'POST',body:form,signal:controller.signal})}catch{throw Error('云端转写连接失败，请稍后重试。')}finally{clearTimeout(timeout)}
 const data=await response.json().catch(()=>({}));if(!response.ok||!data.text)throw Error(data.error||'云端转写暂时不可用。');return String(data.text).trim()
}
function stopVoice(){if(voiceRecorder&&voiceRecorder.state==='recording'){paintVoice('converting','录音已停止，正在通过云端转成文字…');voiceRecorder.stop()}}
async function startVoice(){
 if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){paintVoice('unsupported','当前浏览器无法录音。请使用 Chrome、Edge 或 Safari，并在地址栏允许麦克风。');voiceButton.dataset.supported='false';return}
 voiceBase=input.value.trim();voiceChunks=[];voiceFallbackText='';voiceFallbackError='';
 paintVoice('requesting','正在等待麦克风权限…');
 try{const pendingStream=navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}),timeoutToken={timeout:true};const result=await Promise.race([pendingStream,new Promise(resolve=>setTimeout(()=>resolve(timeoutToken),12000))]);if(result===timeoutToken){pendingStream.then(stream=>stream.getTracks().forEach(track=>track.stop())).catch(()=>{});paintVoice('error','没有收到麦克风授权。Codex 内置浏览器可能不支持录音，请在 Chrome、Edge 或 Safari 打开本站。');return}voiceStream=result}catch(error){const denied=error&&['NotAllowedError','SecurityError'].includes(error.name);paintVoice('error',denied?'麦克风权限未开放。请在地址栏允许后，再点一次“开始听”。':'没有找到可用麦克风，请检查系统输入设备。');return}
 const types=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'];const mimeType=types.find(type=>MediaRecorder.isTypeSupported?.(type))||'';
 try{voiceRecorder=new MediaRecorder(voiceStream,mimeType?{mimeType}:undefined)}catch{releaseVoiceStream();paintVoice('unsupported','当前浏览器无法建立录音。可以继续使用键盘输入。');return}
 voiceRecorder.ondataavailable=event=>{if(event.data?.size)voiceChunks.push(event.data)};
 voiceRecorder.onerror=()=>{clearInterval(voiceTimer);stopBrowserSpeechFallback();releaseVoiceStream();paintVoice('error','录音没有完成，请重新开始。')};
 voiceRecorder.onstop=async()=>{clearInterval(voiceTimer);const blob=new Blob(voiceChunks,{type:voiceRecorder.mimeType||voiceChunks[0]?.type||'audio/webm'});stopBrowserSpeechFallback();releaseVoiceStream();$('#presence-label').textContent='她在听';if(!blob.size){paintVoice('error','没有录到声音，请重新开始。');return}try{const words=await transcribeVoice(blob);input.value=[voiceBase,words].filter(Boolean).join(voiceBase?' ':'');paintVoice('done','已由云端转成文字并写入输入框。请确认内容，再点击发送。');input.focus();input.setSelectionRange(input.value.length,input.value.length)}catch(error){if(voiceFallbackText){input.value=[voiceBase,voiceFallbackText].filter(Boolean).join(voiceBase?' ':'');paintVoice('done','云端转写暂不可用，已使用浏览器识别并写入输入框。请确认后发送。');input.focus();input.setSelectionRange(input.value.length,input.value.length)}else{const hint=voiceFallbackError?'当前浏览器也未能完成备用识别。':'当前浏览器没有可用的备用识别。';paintVoice('error',`${error.message||'云端转写暂时不可用。'} ${hint}请在 Chrome、Edge 或 Safari 打开本站；Codex 的 Quick Annotate 只会发送到 Codex。`)}}syncComposer()};
 voiceRecorder.start(500);startBrowserSpeechFallback();voiceStartedAt=Date.now();paintVoice('listening','正在录音 00:00。说完后点“停止并转文字”。');$('#presence-label').textContent='她在听你说';window.dispatchEvent(new CustomEvent('takagi:voice-recording',{detail:{active:true}}));
 voiceTimer=setInterval(()=>{const elapsed=Math.floor((Date.now()-voiceStartedAt)/1000),seconds=String(elapsed%60).padStart(2,'0');voiceStatus.textContent=`正在录音 00:${seconds}。说完后点“停止并转文字”。`;if(elapsed>=45)stopVoice()},500)
}
voiceButton.dataset.supported=navigator.mediaDevices?.getUserMedia&&window.MediaRecorder?'true':'false';
if(voiceButton.dataset.supported==='false'){inputHint.textContent='可输入、粘贴或拖入图片';paintVoice('unsupported','当前浏览器无法录音。请使用 Chrome、Edge 或 Safari，并允许麦克风。')}
voiceButton.onclick=()=>voiceState==='listening'?stopVoice():startVoice();
window.addEventListener('pagehide',()=>{clearInterval(voiceTimer);stopBrowserSpeechFallback();if(voiceRecorder?.state==='recording')voiceRecorder.stop();releaseVoiceStream()});
async function requestAI(message,image){
 const topicContext=activeTerm?{title:activeTerm.title,tag:activeTerm.tag,summary:activeTerm.summary,detail:activeTerm.detail,scene:activeTerm.scene,opening:termOpening(activeTerm)}:null;
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),image?30000:16000);let response;try{response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,image:image?.dataUrl,password:passwordInput.value,mode:aiMode,scene:activeScene,profile,modelPreference:profile.modelPreference,history:aiHistory.slice(-CHAT_CONTEXT_LIMIT),topicContext}),signal:controller.signal})}catch(error){if(error?.name==='AbortError')throw Error('在线回复等待超时');throw Error('网络连接失败')}finally{clearTimeout(timeout)}
 const data=await response.json().catch(()=>({}));if(!response.ok){const failure=Error(data.error||'在线模型暂时不可用');failure.code=data.code||'';failure.status=response.status;throw failure}try{sessionStorage.setItem('takagi-ai-password',passwordInput.value)}catch{}forgetPassword.hidden=false;passwordStatus.textContent='密码已验证并保存在当前标签页。刷新后仍可用，关闭标签页或点击“清除”后失效。';
 if(!data||typeof data.text!=='string'||!data.text.trim())throw Error('在线模型返回了空内容');
 return{text:data.text.trim(),mood:data.mood||'listening',topic:data.topic||'chat',suggestions:Array.isArray(data.suggestions)?data.suggestions.slice(0,4):[],knowledgeTags:Array.isArray(data.knowledgeTags)?data.knowledgeTags:[]};
}
const topicLexicons={
 '中日饮食':['吃','饭','菜','茶','早餐','午餐','晚餐','夜宵','料理','和食','味噌','便当','食堂','口味','忌口','外卖'],
 '作息文化':['睡','困','熬夜','早起','起床','午睡','作息','加班','通勤','自习','休息','效率'],
 '天气气候':['天气','下雨','雨季','梅雨','台风','降温','炎热','寒冷','下雪','湿度','风','带伞'],
 '地理常识':['地理','旅行','城市','地区','南方','北方','关东','关西','北海道','九州','高原','盆地','沿海'],
 '中国校园':['学校','校园','月考','晚自习','食堂','同学','放学'],
 '原作背景':['原作','高木','西片','剧情','漫画','动画','角色'],
 '人物语气':['玩笑','捉弄','认真','语气','聊天','距离'],
 '成年日常':['下班','回家','通勤','周末','今天','一天','无聊','休息','放空'],
 '关系与边界':['朋友','同事','室友','家人','对象','伴侣','误会','冷战','吵架','拒绝','边界'],
 '选择与计划':['选择','纠结','决定','计划','拖延','该不该','目标','开始','坚持'],
 '兴趣与作品':['音乐','歌','电影','动画','漫画','小说','游戏','摄影','运动','作品'],
 '季节与生活':['春天','夏天','秋天','冬天','蝉','樱花','烟花','暑假','季节'],
 '情绪整理':['焦虑','难过','委屈','烦','压力','孤独','生气','失望','心情'],
 '学习与复盘':['学习','复习','考试','论文','作业','题目','卡住','专注','复盘'],
 '日本青春':['放课后','图书室','部活','汽水','短歌','便笺','车站','雨宿り','鞋柜','回信','花火','烟花','归途','青春']
};
function termPrompts(t){const map={
 '中日饮食':['说说我今天吃的','比较一道中日料理','从茶和待客聊起','按我的地区推荐话题'],
 '作息文化':['我最近总熬夜','比较校园与职场作息','帮我调整一个习惯','先问我的时间表'],
 '天气气候':['我这里今天的天气','日本不同地区差多少','天气会怎样影响吃饭','聊聊雨天的感觉'],
 '地理常识':['从我的城市开始','地形怎样影响饮食','想去日本哪一带','比较两个地区'],
 '原作背景':['聊人物关系','聊叙事节奏','说说我在意的情节','回到日常话题'],
 '中国校园':['这让我想到我的学校','聊聊放学后的记忆','比较不同校园生活','换一个具体场景'],
 '成年日常':['复盘今天的一件事','我只想放松一下','聊聊下班路上','安排一个周末'],
 '关系与边界':['先讲事实','先讲我的感受','帮我组织一句话','一起判断边界'],
 '选择与计划':['列出两个选项','先看最坏结果','找一个可逆步骤','帮我拆第一步'],
 '兴趣与作品':['从一首歌聊起','聊最近看的作品','问我一个具体细节','它和一段记忆有关'],
 '季节与生活':['说说我这里的季节','从一种声音聊起','聊季节里的食物','这让我想到一段记忆'],
 '情绪整理':['先听我说完','帮我区分感受','一起找最重的部分','先安静一会儿'],
 '学习与复盘':['检查我卡住的步骤','区分三类问题','只提示下一步','给我一道变式'],
 '日本青春':['先描写眼前的场景','从一个声音开始','问我当时没说的话','把它写成五行短句']
 };return(map[t.tag]||['这和我的经历有关','先问我一个具体问题','换个角度聊','回到今天']).slice(0,4)}
function termOpening(t){const place=profile.location?`你在${profile.location}，所以我先不把地域差异说得太笼统。`:'';const openings={
 '中日饮食':`${place}“${t.title}”如果只列知识会有点干。先从你今天真正吃过或想吃的一样东西开始吧，我再把地域和习惯接进来。`,
 '作息文化':`聊“${t.title}”之前，我想先知道你的真实一天。最近最难守住的是起床、吃饭、专注，还是入睡？`,
 '天气气候':`${place}气候是长期背景，今天的天气才会影响你的心情和安排。你那里现在具体是冷、热、下雨，还是风很大？`,
 '地理常识':`${place}地图只有落到一天的生活里才有意思。你更想从旅行、吃饭、通勤，还是季节变化进入“${t.title}”？`,
 '原作背景':`“${t.title}”可以聊设定，也可以聊它为什么让人记住。你更在意人物之间的距离，还是某个情节带来的感觉？`,
 '人物语气':`“${t.title}”放到真实聊天里，关键是观察和分寸。你想让我用一个小玩笑示范，还是认真拆解这种说话节奏？`,
 '中国校园':`“${t.title}”只是入口。你自己的校园经历里，有没有一个相似的下午、声音或人？`,
 '成年日常':`先不概括整天。就从“${t.title}”里最具体的一个瞬间开始吧，你更想复盘、解决，还是只说给我听？`,
 '关系与边界':`聊“${t.title}”时，我想先分清发生了什么和你怎样理解它。你希望我先听、帮你梳理，还是一起组织要说的话？`,
 '选择与计划':`“${t.title}”先不急着下结论。你最想保住什么，哪种结果又是你不能接受的？`,
 '兴趣与作品':`“${t.title}”如果只交换名称就太可惜了。你最先记住的是声音、画面、人物，还是当时的自己？`,
 '季节与生活':`${place}说到“${t.title}”，你此刻最明显感受到的是温度、光线、声音，还是某种味道？`,
 '情绪整理':`如果“${t.title}”暂时还说不清，可以先告诉我身体哪里最紧、脑中哪句话一直重复，或者你现在最不想面对什么。`,
 '学习与复盘':`“${t.title}”先看证据。把目标、已经做过的步骤和最不确定的一处告诉我，我们只处理真正卡住的地方。`,
 '日本青春':`${t.detail.split('。')[1]||t.summary} 先别急着概括。你在这个画面里最先注意到的是光、声音、动作，还是一句没说出口的话？`
 };return openings[t.tag]||`“${t.title}”可以从事实，也可以从你的经历开始。你更想先讲哪一边？`}
function selectLocalTerm(message){const text=message.toLowerCase();let best=activeTerm,bestScore=activeTerm?2:0;for(const term of terms){let score=0;if(text.includes(term.title.toLowerCase()))score+=6;for(const word of topicLexicons[term.tag]||[])if(text.includes(word))score+=2;if(profile.interests?.some(item=>term.tag.includes(item.replace('与生活','').replace('与季节','').replace('与旅行',''))))score++;if(score>bestScore){best=term;bestScore=score}}return bestScore>=2?best:null}
function localKnowledgeReply(message){const term=selectLocalTerm(message);if(!term)return null;activeTerm=term;localTopicTurns++;const prompts=termPrompts(term),place=profile.location?.trim(),fact=(term.detail.split('。').find(part=>part.length>12)||term.summary).trim();let text='';
 if(term.tag==='中日饮食')text=/比较|区别|一样吗/.test(message)?`可以比较，但先固定一个具体对象。就“${term.title}”来说，${fact}。你想比较做法、用餐场景，还是它背后的地域原因？`:`你提到的细节比“中餐或日料”这种大标签有用。${place?`结合你在${place}的日常，`:''}你更在意口味、时间、预算，还是和谁一起吃？`;
 else if(term.tag==='作息文化')text=/几[点时]|多久|小时/.test(message)?`${fact}。这个只能作一般参考，我还需要知道你固定起床时间和白天最困的时段，才能把建议放进真实作息。`:`先不急着做完整时间表。你最近哪一个时段最容易失控，发生前通常在做什么？`;
 else if(term.tag==='天气气候')text=/今天|现在|明天|温度|预报/.test(message)?`我没有实时气象数据，不能替你报具体温度或降雨概率。${place?`你设置在${place}，`:''}把今天看到的天气告诉我，我可以继续判断它会怎样影响通勤、吃饭和心情。`:`${fact}。你想聊长期气候差异，还是今天这场天气带来的具体感受？`;
 else if(term.tag==='地理常识')text=`${fact}。如果把它放回生活里，地形会继续影响气候、交通和吃什么。${place?`从${place}出发，`:''}你最想沿哪条线索展开？`;
 else if(term.tag==='原作背景')text=`${fact}。比起复述剧情，我更想知道你为什么点开它：是人物之间的距离、叙事节奏，还是某个细节像你经历过的事？`;
 else if(term.tag==='成年日常')text=`${fact}。先选一种节奏吧：把今天复盘清楚、处理一个具体问题，还是只让我陪你说几句？`;
 else if(term.tag==='关系与边界')text=`${fact}。你希望我先听事实、帮你区分感受，还是一起整理一句能对对方说的话？`;
 else if(term.tag==='选择与计划')text=`${fact}。先告诉我你最想保住什么，以及哪种结果最不能接受，我们再比较选项。`;
 else if(term.tag==='兴趣与作品')text=`${fact}。它最先留给你的是一个声音、画面、人物，还是某段和作品连在一起的生活？`;
 else if(term.tag==='季节与生活')text=`${fact}。${place?`你在${place}，`:''}此刻最明显的季节线索是什么？`;
 else if(term.tag==='情绪整理')text=`${fact}。你现在更希望我听完整、帮你找最重的部分，还是先安静一下？`;
 else if(term.tag==='学习与复盘')text=`${fact}。把你已经做过的步骤和最不确定的一处发来，我只从那里继续。`;
 else if(term.tag==='日本青春')text=localTopicTurns%3===1?`${fact}。先选一个细节吧：光、声音、动作，或者当时没说出口的话。`:localTopicTurns%3===2?`我还记得我们在聊“${term.title}”。如果镜头再往前走十秒，你觉得谁会先开口，又会说什么？`:`这个画面已经有一点轮廓了。你想把它留成一句话、五行短句，还是继续讲当时真正发生的事？`;
 else text=localTopicTurns%2?`${term.summary}。这句话落到你身上，最接近的是哪一段具体经历？`:`我记得我们正在聊“${term.title}”。你刚才那句话里，最值得继续的是哪个细节？`;
 return{text,mood:/睡|累|雨|情绪/.test(message)?'quiet':'listening',topic:'term-'+term.tag,suggestions:prompts,knowledgeTags:[term.tag]}
}
function startTermConversation(t){activeTerm=t;localTopicTurns=0;dialog.close();if(activeScene!==t.scene)setScene(t.scene);const opening=termOpening(t);addContext(`${scenes[t.scene].name} · “${t.title}”这条线索会在后续对话中保留`);add('assistant',opening);speak(opening,t.tag==='人物语气'?'playful':'warm');renderSuggestions(termPrompts(t));aiHistory.push({role:'assistant',text:`【当前话题：${t.title}】${opening}`});aiHistory.splice(0,Math.max(0,aiHistory.length-CHAT_CONTEXT_LIMIT));saveSessionHistory();document.querySelector('.chat').scrollIntoView({behavior:'smooth',block:'center'});input.focus()}
function renderProfileSummary(){const box=$('#profile-summary');if(!box)return;const modelNames={local:'本地陪伴','gpt-5.6-luna':'GPT 5.6 Luna','gpt-5.6-terra':'GPT 5.6 Terra','deepseek-flash':'DeepSeek Flash'};const styleNames={gentle:'轻松同桌',playful:'俏皮观察',direct:'认真直说',analytical:'条理分析',quiet:'少说一点'};const moodNames={calm:'平静',tired:'有点累',happy:'心情不错',anxious:'有些焦虑',low:'情绪低落',focused:'想专注'};box.replaceChildren();const words=document.createElement('span');words.append(textEl('strong',preferredAddress()),textEl('small',`${modelNames[profile.modelPreference]||'本地陪伴'} · ${styleNames[profile.chatStyle]||'轻松同桌'} · ${moodNames[profile.currentMood]||'平静'}`));box.append(words,textEl('em','调整 ›'));box.title=profile.context?`当前情境：${profile.context}`:'设置模型、称呼、心情和当前情境';const status=$('#ai-status');if(status&&!busy)status.textContent=profile.modelPreference==='local'?'本地陪伴引擎 · 已结合称呼、心情与当前情境':`${modelNames[profile.modelPreference]||'在线模型'} · 访问密码由 Netlify Function 校验`}
let quietMode=false,lastActivity=Date.now(),lastPromptAt=Date.now(),idleIndex=0;
function markActivity(){lastActivity=Date.now();}
const baseSceneInteract=interact;
interact=function(action){
 const chapterLines={
  chocolate:['猜得这么快，会让我怀疑你从早上就在等。再猜一次：是义理巧克力，还是我只想给你的？','她用指尖轻轻按住纸袋。'],
  gift:['我收下了。价格先不问，我更想知道，你挑它的时候想到的是我的哪一点。','回礼被轻轻接了过去。'],
  reason:['让我猜：你怕挑得太郑重，也怕显得随便，所以在两种东西之间犹豫了很久。对吗？','她看了看礼物，又看向你。'],
  stall:['先选一个。苹果糖、捞金鱼，还是站在旁边看别人挑战射的？只能选一个哦。','摊位的灯在身后亮起来。'],
  fireworks:['还有一点时间。第一束升起来的时候，你可别只顾着看天空，忘了刚才想说的话。','远处传来烟花试放的闷响。'],
  find:['走散的话，不准只说“在摊位旁边”。告诉我一个只有我们刚才注意到的东西，我就去那里找你。','人群从你们身边慢慢经过。']
 };
 if(action==='note'&&activeScene==='valentine')chapterLines.note=['纸条上只有一句：你先猜，我再告诉你。','一张折好的纸条停在纸袋旁边。'];
 if(action==='walk'&&activeScene==='whiteDay')chapterLines.walk=['走吧。回礼的理由可以路上慢慢说，我暂时不催你。','她放慢脚步，等你并肩。'];
 if(action==='walk'&&activeScene==='festival')chapterLines.walk=['跟紧一点。等走到能看见天空的地方，再决定站哪边。','她在人群边回头确认你还在。'];
 if(action==='stay'&&['valentine','whiteDay','festival'].includes(activeScene)){setQuiet(true);chapterLines.stay=activeScene==='valentine'?['那就等铃声。纸袋先放在这里，看你还能忍住多久不问。','你们一起等着放学铃。']:activeScene==='whiteDay'?['慢慢说。我想听你挑这个回礼时真正考虑了什么。','三月的暮色停在桌边。']:['好，先站在这里。等第一束烟花升起来再说。','你们暂时把话留到烟花开始。']}
 const item=chapterLines[action];
 if(!item)return baseSceneInteract(action);
 speak(item[0],action==='find'?'playful':'warm');addContext(item[1]);add('assistant',item[0]);return{action,reply:item[0]};
};
function setQuiet(value){if(!value&&dialogue.topic==='quiet')dialogue.topic='';quietMode=value;$('#quiet-mode').setAttribute('aria-pressed',String(value));$('#quiet-mode').textContent=value?'正在安静陪伴 · 继续聊天':'安静陪伴';$('#presence-label').textContent=value?'不用说话，坐一会儿就好':'她在听';sceneEl.dataset.mood=value?'quiet':'listening';if(value)speak('嗯，不用找话题。我们就这样坐一会儿。');return {quiet:value};}
$('#quiet-mode').onclick=()=>setQuiet(!quietMode);
async function submit(text=input.value){
 const attachment=pendingImage;if(busy||(!text.trim()&&!attachment))return;if(profile.modelPreference!=='local'&&!passwordInput.value.trim()){passwordStatus.textContent='请先输入 AI 访问密码，再发送消息。';passwordInput.focus();return}
 const sent=text.trim().slice(0,1200)||(attachment?'请看看这张图片，先说出你确实观察到的内容，再自然地和我聊下去。':'');markActivity();if(quietMode)setQuiet(false);if(attachment&&profile.modelPreference!=='deepseek-flash'){profile.modelPreference='deepseek-flash';save('takagi-profile',JSON.stringify(profile));renderProfileSummary();addContext('图片识别已切换到 DeepSeek Flash。')}busy=true;const userRow=add('user',text.trim().slice(0,1200)||(attachment?'发来一张图片。':sent));if(attachment){const image=document.createElement('img');image.src=attachment.dataUrl;image.alt=attachment.name;image.className='message-image';userRow.append(image)}input.value='';pendingImage=null;attachmentPreview.hidden=true;attachmentPreview.replaceChildren();syncComposer();
 document.querySelectorAll('#suggestions button').forEach(b=>b.disabled=true);
 sceneEl.dataset.mood='listening';$('#presence-label').textContent='她正在听';speak(aiMode==='study'?'让我看看这一步。':'嗯，我在听。','listening');
 const typing=textEl('p','高木正在想怎么回答…','typing');log.append(typing);log.scrollTop=log.scrollHeight;
let response,online=profile.modelPreference!=='local';try{if(!online)throw Error('local');response=await requestAI(sent,attachment);const modelLabel=profile.modelPreference==='deepseek-flash'?'DeepSeek Flash':'在线模型';$('#ai-status').textContent=response.knowledgeTags.length?`${modelLabel} 在线 · 本轮参考：${response.knowledgeTags.join('、')}`:`${modelLabel} 在线 · 已结合个性设置与本次短期上下文`;}catch(error){online=false;if(error?.code==='INVALID_ADMIN_PASSWORD'||error?.code==='PASSWORD_NOT_CONFIGURED'){try{sessionStorage.removeItem('takagi-ai-password')}catch{}passwordInput.value='';forgetPassword.hidden=true;passwordStatus.textContent=error.code==='PASSWORD_NOT_CONFIGURED'?'站点尚未配置 AI 访问密码，请联系站点管理员。':'密码不正确，请重新输入后再发送。';response={text:error.code==='PASSWORD_NOT_CONFIGURED'?'站点还没有配置 AI 访问密码，暂时无法连接 DeepSeek。':'密码没有通过校验，刚才的内容没有发送给 DeepSeek。请重新输入密码后再试。',mood:'quiet',topic:'password-error',suggestions:[],knowledgeTags:[]}}else if(attachment)response={text:'图片已经附在这轮消息里，但在线识别刚才没有完成。你可以重新发一次，或者告诉我希望我先看人物、文字还是整体氛围。',mood:'quiet',topic:'image-retry',suggestions:['重新发送图片','先看图片里的文字','先聊整体氛围','换成文字描述'],knowledgeTags:[]};else response=window.companionLocalReply?window.companionLocalReply(sent,dialogue,activeScene,aiMode,localKnowledgeReply):dialogue.reply(sent,activeScene,aiMode);const unavailable=profile.modelPreference==='deepseek-flash'?'DeepSeek Flash':'在线模型',reason=error?.message&&error.message!=='local'?`：${error.message}`:'';$('#ai-status').textContent=error?.code==='INVALID_ADMIN_PASSWORD'?'DeepSeek 未调用 · AI 访问密码不正确':error?.code==='PASSWORD_NOT_CONFIGURED'?'DeepSeek 未调用 · 站点尚未配置 AI 访问密码':attachment?`图片识别暂时未完成${reason} · 图片没有写入长期记忆`:response.knowledgeTags?.length?`本地话题引擎 · 当前词条：${response.knowledgeTags.join('、')}`:profile.modelPreference==='local'?'本地陪伴引擎 · 已结合称呼、心情与当前情境':`${unavailable}${reason} · 已切换本地陪伴回复`;}
 rememberTurn(sent+(attachment?' [本轮附有图片]':''),response.text);
 await new Promise(r=>setTimeout(r,online?80:150+Math.min(sent.length*4,180)));typing.remove();
 sceneEl.dataset.mood=response.mood;sceneEl.classList.add('speaking');$('#presence-label').textContent=response.mood==='quiet'?'陪你坐一会儿':'她轻声说';
 const row=textEl('div','','message assistant');row.append(assistantHeader(response.mood));const p=textEl('p','');row.setAttribute('aria-hidden','true');row.append(p);log.append(row);
 const chars=Array.from(response.text);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||load('takagi-text-speed')==='instant';
 let skip=false;const complete=textEl('button','显示整句','reply-complete');complete.type='button';complete.onclick=()=>{skip=true};row.append(complete);
 if(reduced){p.textContent=response.text;}else{for(let i=0;i<chars.length;i+=3){if(skip||document.hidden){p.textContent=response.text;break}p.textContent+=chars.slice(i,i+3).join('');if(log.scrollHeight-log.scrollTop-log.clientHeight<160)log.scrollTop=log.scrollHeight;await new Promise(r=>setTimeout(r,24));}}
 complete.remove();
 row.removeAttribute('aria-hidden');attachReactions(row);speak(response.text,response.mood);sceneEl.classList.remove('speaking');busy=false;turn++;syncComposer();renderSuggestions(response.suggestions);
 document.querySelectorAll('#suggestions button').forEach(b=>b.disabled=false);$('#presence-label').textContent='她在听';if(response.topic==='quiet')setQuiet(true);renderMemory();markActivity();
}
chatForm.onsubmit=e=>{e.preventDefault();submit()};input.oninput=()=>{syncComposer();markActivity();if(!busy){sceneEl.dataset.mood='listening';$('#presence-label').textContent=input.value?'慢慢写，她在等你':'她在听';}};
input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();submit()}};
function renderMemory(){const box=$('#memory-strip');if(!box)return;const items=dialogue.memorySummary(),sessionTurns=Math.floor(aiHistory.length/2);box.replaceChildren();if(!items.length&&!sessionTurns){box.hidden=true;return}box.hidden=false;box.append(textEl('span',sessionTurns?`短期记忆 · 已记录 ${Math.min(aiHistory.length,CHAT_CONTEXT_LIMIT)} / ${CHAT_CONTEXT_LIMIT} 条消息`:`短期记忆 · 最多 ${CHAT_CONTEXT_LIMIT} 条消息`));items.forEach(item=>box.append(textEl('small',item)))}
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{if(busy||button.dataset.mode===aiMode)return;aiMode=button.dataset.mode==='study'?'study':'chat';save('takagi-chat-mode',aiMode);document.querySelectorAll('[data-mode]').forEach(item=>item.setAttribute('aria-pressed',String(item.dataset.mode===aiMode)));syncChatContext();renderSuggestions();addContext(aiMode==='study'?'她把练习册往你这边挪了挪。把题目和已经想到的步骤写下来吧。':'她合上练习册，重新看向你。想从哪件小事聊起？');$('#bubble').textContent=aiMode==='study'?'先看题目。你已经想到哪一步了？':'好，先聊一会儿。';input.focus()});
sceneEl.addEventListener('pointermove',e=>{if(!sceneEl.classList.contains('alive')||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const rect=sceneEl.getBoundingClientRect();sceneEl.style.setProperty('--look-x',((e.clientX-rect.left)/rect.width-.5)*9+'px');sceneEl.style.setProperty('--look-y',((e.clientY-rect.top)/rect.height-.5)*5+'px');});
sceneEl.addEventListener('pointerleave',()=>{sceneEl.style.setProperty('--look-x','0px');sceneEl.style.setProperty('--look-y','0px')});
setInterval(()=>{if(document.hidden||quietMode||busy||focusTimer||input.value||dialog.open||Date.now()-lastActivity<90000||Date.now()-lastPromptAt<180000)return;const lines=['不用一直找话题。坐一会儿也可以。','你忙你的，想说话时再开口。','今天还有什么小事，想留到现在讲吗？'];speak(lines[idleIndex++%lines.length]);lastPromptAt=Date.now()},15000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)markActivity()});
const dialog=$('#dialog');function openDialog(title,body){$('#dialog-title').textContent=title;$('#dialog-body').replaceChildren(body);dialog.showModal()}$('#close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});function textEl(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e}
function renderTermPreview(){const box=$('#term-preview');box.replaceChildren();const same=terms.filter(t=>t.scene===activeScene),featured=[...same.filter(t=>t.tag==='日本青春'),...same.filter(t=>t.tag!=='日本青春')].slice(0,4);featured.forEach(t=>{const b=textEl('button',t.title,'term-card');b.dataset.tag=t.tag;b.append(textEl('small',t.tag),textEl('span',t.summary));b.onclick=()=>openTerm(t);box.append(b)})}
function openTerm(t){const body=document.createElement('div');body.append(textEl('span',t.tag,'term-tag'),textEl('p',t.detail));if(t.source)body.append(link('查看官方资料 ↗',t.source));body.append(textEl('h3','她会这样接话'),textEl('p',termOpening(t),'term-opening'));const button=textEl('button','从这个话题开始聊','setting');button.onclick=()=>startTermConversation(t);body.append(button);openDialog(t.title,body)}
function showGlossary(){const body=document.createElement('div');body.className='term-dialog';body.append(textEl('p','这些词条区分原作背景、人物语气、生活文化、成年话题与原创情景。'));const search=document.createElement('input');search.type='search';search.placeholder='搜索词条';search.setAttribute('aria-label','搜索词条');body.append(search);const filters=document.createElement('div');filters.className='term-filters';const list=document.createElement('div');list.className='term-list';let filter='全部';function render(){list.replaceChildren();const q=search.value.trim();const shown=terms.filter(t=>(filter==='全部'||t.tag===filter)&&(!q||t.title.includes(q)||t.summary.includes(q)||t.detail.includes(q)));shown.forEach(t=>{const b=textEl('button',t.title,'term-row');b.append(textEl('small',t.tag),textEl('span',t.summary));b.onclick=()=>openTerm(t);list.append(b)});if(!shown.length)list.append(textEl('p','没有找到相关词条。'))}['全部','日本青春','原作背景','人物语气','中国校园','成年日常','关系与边界','选择与计划','兴趣与作品','情绪整理','学习与复盘','中日饮食','作息文化','天气气候','地理常识','原创互动','互动约定'].forEach(f=>{const b=textEl('button',f);b.setAttribute('aria-pressed',String(filter===f));b.onclick=()=>{filter=f;filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x.textContent===f)));render()};filters.append(b)});search.oninput=render;body.append(filters,list);render();openDialog('日常词条',body);search.focus()}
$('#glossary-open').onclick=showGlossary;$('#all-terms').onclick=showGlossary;
function openProfileSettings(){
 const form=document.createElement('form');form.className='profile-form';
 const makeField=(labelText,control,hint='')=>{const label=textEl('label',labelText,'profile-field');label.append(control);if(hint)label.append(textEl('small',hint));return label};
 const name=document.createElement('input');name.name='name';name.maxLength=12;name.value=profile.name;name.placeholder='选填，例如 林夏';
 const address=document.createElement('input');address.name='address';address.maxLength=12;address.value=profile.address;address.placeholder='例如 同桌、小林';
 const identity=document.createElement('select');['学生','大学生','职场中','自由职业','其他'].forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;option.selected=profile.identity===value;identity.append(option)});
 const location=document.createElement('input');location.name='location';location.maxLength=30;location.value=profile.location||'';location.placeholder='选填，例如 上海、成都、东京';
 const difficulty=document.createElement('select');difficulty.name='difficulty';[['easy','入门 · 单步字谜与常识'],['medium','进阶 · 两步条件与语言转换'],['hard','成人挑战 · 多步逻辑与概率'],['expert','高阶 · 信息论、组合与反直觉推理']].forEach(([value,label])=>{const option=textEl('option',label);option.value=value;difficulty.append(option)});difficulty.value=['easy','medium','hard','expert'].includes(profile.difficulty)?profile.difficulty:'hard';
 const model=document.createElement('select');model.name='model';[['deepseek-flash','DeepSeek Flash · 默认在线模型',false],['local','本地陪伴引擎 · 无需联网',false],['gpt-5.6-luna','GPT 5.6 Luna · 当前暂不支持',true],['gpt-5.6-terra','GPT 5.6 Terra · 当前暂不支持',true]].forEach(([value,label,disabled])=>{const option=textEl('option',label);option.value=value;option.disabled=disabled;model.append(option)});model.value=['local','deepseek-flash'].includes(profile.modelPreference)?profile.modelPreference:'deepseek-flash';
 const chatStyle=document.createElement('select');chatStyle.name='chatStyle';[['gentle','轻松同桌 · 自然、温和'],['playful','俏皮观察 · 适量小玩笑'],['direct','认真直说 · 少些铺垫'],['analytical','条理分析 · 先拆清楚'],['quiet','少说一点 · 留出停顿']].forEach(([value,label])=>{const option=textEl('option',label);option.value=value;chatStyle.append(option)});chatStyle.value=['gentle','playful','direct','analytical','quiet'].includes(profile.chatStyle)?profile.chatStyle:'gentle';
 const currentMood=document.createElement('select');currentMood.name='currentMood';[['calm','平静'],['tired','有点累'],['happy','心情不错'],['anxious','有些焦虑'],['low','情绪低落'],['focused','想专注']].forEach(([value,label])=>{const option=textEl('option',label);option.value=value;currentMood.append(option)});currentMood.value=['calm','tired','happy','anxious','low','focused'].includes(profile.currentMood)?profile.currentMood:'calm';
 const context=document.createElement('textarea');context.name='context';context.maxLength=120;context.value=profile.context;context.placeholder='例如：工作转换期、准备考试、最近在处理一段关系';
 const startScene=document.createElement('select');[['last','继续上次打开的 Chapter'],['classroom','放学教室'],['cafeteria','食堂午后'],['study','晚自习'],['rain','雨天走廊'],['valentine','2月14日'],['whiteDay','3月14日'],['festival','夏日祭']].forEach(([value,label])=>{const option=textEl('option',label);option.value=value;startScene.append(option)});startScene.value=profile.startScene&&['last',...Object.keys(scenes)].includes(profile.startScene)?profile.startScene:'last';
 const startMode=document.createElement('select');[['last','继续上次使用的模式'],['chat','日常聊天'],['study','学习陪伴']].forEach(([value,label])=>{const option=textEl('option',label);option.value=value;startMode.append(option)});startMode.value=['last','chat','study'].includes(profile.startMode)?profile.startMode:'last';
 const guide=textEl('p','聊天默认使用 DeepSeek Flash，由 Netlify Function 调用。GPT API 当前暂不支持。游戏难度仍可独立选择。偏好保存在当前浏览器；短期聊天记忆只保留在当前标签页会话。','profile-guide');
 form.append(guide,textEl('h3','回应方式','profile-section-title'),makeField('对话引擎',model,'DeepSeek Flash 由 Netlify Function 调用，API 密钥不会进入浏览器。GPT API 当前暂不支持，选项已标记并停用；在线服务不可用时会使用本地回退。'),makeField('她的说话方式',chatStyle,'控制回应的节奏、直接程度和玩笑密度，不改变事实内容。'),makeField('你现在的心情',currentMood,'用于调整回应强度和节奏，可以随时修改。'),textEl('h3','关于你','profile-section-title'),makeField('你的名字',name,'选填。只用于称呼和个性化回应，不会展示给其他访问者。'),makeField('希望她怎么称呼你',address,'对话和 Chapter 开场优先使用此称呼；留空时使用“同桌”。'),makeField('你现在的身份',identity,'用于选择更合适的学习、工作或日常例子。'),makeField('所在地区',location,'选填。用于区分天气、饮食和生活节奏；页面不会自动获取定位。'),textEl('h3','进入页面时','profile-section-title'),makeField('首选 Chapter',startScene,'选择固定 Chapter，或继续上次离开时的场景。'),makeField('首选对话模式',startMode,'可以固定进入日常聊天或学习陪伴，也可以继续上次选择。'),textEl('h3','内容偏好','profile-section-title'),makeField('谜题难度',difficulty,'入门偏单步提示；成人挑战与高阶档会增加条件数量、推理步骤和反直觉题。'),makeField('当前情境',context,'选填，最多 120 字。写明最近的目标、处境或想聊的方向，连续回答会更准确。'));
 const interestFieldset=document.createElement('fieldset');interestFieldset.className='need-options';interestFieldset.append(textEl('legend','希望了解的话题 · 最多 4 项'));['中日饮食','作息与生活','天气与季节','地理与旅行'].forEach(value=>{const label=document.createElement('label');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.value=value;checkbox.checked=(profile.interests||[]).includes(value);checkbox.onchange=()=>{const checked=interestFieldset.querySelectorAll('input:checked');if(checked.length>4){checkbox.checked=false;interestNote.textContent='最多选择 4 项。';interestNote.hidden=false}};label.append(checkbox,document.createTextNode(value));interestFieldset.append(label)});const interestNote=textEl('small','','profile-note');interestFieldset.append(interestNote);form.append(interestFieldset);
 const fieldset=document.createElement('fieldset');fieldset.className='need-options';fieldset.append(textEl('legend','这次更需要什么 · 最多 3 项'));['轻松陪伴','认真倾听','学习督促','情绪整理','日常闲聊','任务规划'].forEach(value=>{const label=document.createElement('label');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.value=value;checkbox.checked=profile.needs.includes(value);checkbox.onchange=()=>{const checked=fieldset.querySelectorAll('input:checked');if(checked.length>3){checkbox.checked=false;const note=fieldset.querySelector('small');note.textContent='最多选择 3 项。';note.hidden=false}};label.append(checkbox,document.createTextNode(value));fieldset.append(label)});fieldset.append(textEl('small','','profile-note'));form.append(fieldset);
 const actions=document.createElement('div');actions.className='profile-actions';const saveButton=textEl('button','保存并应用','profile-save');saveButton.type='submit';const motionButton=textEl('button',sceneEl.classList.contains('alive')?'暂停人物动态':'开启人物动态','profile-motion');motionButton.type='button';motionButton.onclick=()=>{$('#motion').click();motionButton.textContent=sceneEl.classList.contains('alive')?'暂停人物动态':'开启人物动态'};const resetButton=textEl('button','填写默认值','profile-reset');resetButton.type='button';resetButton.onclick=()=>{name.value='';address.value='同桌';identity.value='学生';location.value='';difficulty.value='hard';model.value='deepseek-flash';chatStyle.value='gentle';currentMood.value='calm';startScene.value='last';startMode.value='last';context.value='';interestFieldset.querySelectorAll('input').forEach(input=>input.checked=false);fieldset.querySelectorAll('input').forEach(input=>input.checked=input.value==='轻松陪伴');const note=fieldset.querySelector('small');note.textContent='默认值已填入，点击“保存并应用”后生效。';note.hidden=false};const clearButton=textEl('button','清除本机偏好','profile-clear');clearButton.type='button';clearButton.onclick=()=>{if(!confirm('清除这台设备上的称呼、场景、短期对话、游戏与音乐偏好？本地相册和青春诗笺不会被删除。'))return;['takagi-profile','takagi-scene','takagi-motion','takagi-pose','takagi-chat-mode','takagi-arcade-difficulty','takagi-arcade-last-game','takagi-lateral-mode','takagi-music-scene','takagi-music-effects','takagi-music-fit','takagi-guide-seen-v1'].forEach(key=>{try{localStorage.removeItem(key)}catch{}});try{sessionStorage.removeItem('takagi-chat-session');sessionStorage.removeItem('takagi-ai-password')}catch{}location.reload()};actions.append(saveButton,motionButton,resetButton,clearButton);form.append(actions);
 form.onsubmit=e=>{e.preventDefault();const needs=Array.from(fieldset.querySelectorAll('input:checked'),item=>item.value).slice(0,3);const interests=Array.from(interestFieldset.querySelectorAll('input:checked'),item=>item.value).slice(0,4);profile={name:name.value.trim(),address:address.value.trim()||'同桌',identity:identity.value,location:location.value.trim(),difficulty:difficulty.value,difficultyVersion:3,context:context.value.trim(),interests,needs:needs.length?needs:['轻松陪伴'],modelPreference:model.value,chatStyle:chatStyle.value,currentMood:currentMood.value,startScene:startScene.value,startMode:startMode.value};save('takagi-profile',JSON.stringify(profile));dialogue.setProfile(profile);window.dispatchEvent(new Event('takagi-profile-change'));renderProfileSummary();renderSuggestions();syncChatContext();dialog.close();const line=`记住了，${preferredAddress()}。${profile.context?`最近是“${profile.context}”，我会留意。`:'我们慢慢聊。'}`;addContext(`${preferredAddress()}的个性设置已更新。`);add('assistant',line);speak(line,'warm')};
 openDialog('个性设置 · 回应偏好',form);model.focus()
}$('#settings').onclick=openProfileSettings;$('#profile-summary').onclick=openProfileSettings;renderProfileSummary();
function showGuide(){const body=document.createElement('div');body.className='guide-dialog';body.append(textEl('p','使い方 · 先选场景，再决定聊天、游戏或写诗。所有偏好都可以稍后调整。','guide-lead'));const steps=document.createElement('ol');[['选择 Chapter','左侧 Chapter 控制画面、开场和互动。高木会从教室、雨天、晚自习等细节继续轻微捉弄和校园话题。'],['设置对话','聊天默认使用 DeepSeek Flash，支持文字、图片与短期连续对话。GPT API 当前暂不支持，页面已标记。'],['输入与记忆','每条最多 1200 字。最近 12 条消息在当前标签页会话内用于承接上下文，显示为“已记录数量 / 12”。刷新仍保留，关闭标签页后清除。'],['密码与用量','密码在第一次成功对话后保存在当前标签页，刷新后仍可用；关闭标签页或点击“清除”后失效。每次请求仍由 Netlify Function 校验。当前版本未设置两小时有效期、个人调用次数或每日额度。'],['小游戏','难度始终由玩家在个性设置中选择。“一句话推理”可使用 DeepSeek 智能判断，也可使用本地题库。'],['青春诗笺','“诗集分享”可以阅读古诗与原创日文短句，也可以保存、修改自己的青春诗歌，并请 DeepSeek 提供润色稿。']].forEach(([title,detail])=>{const item=document.createElement('li');item.append(textEl('strong',title),textEl('span',detail));steps.append(item)});body.append(steps);const actions=document.createElement('div');actions.className='guide-actions';const settingsButton=textEl('button','打开个性设置','setting');settingsButton.onclick=()=>{dialog.close();openProfileSettings()};const poemButton=textEl('button','打开诗集分享','setting');poemButton.onclick=()=>{dialog.close();$('#poetry-open')?.click()};const accessButton=textEl('button','查看隐私说明','setting');accessButton.onclick=()=>{dialog.close();$('#access-open').click()};actions.append(settingsButton,poemButton,accessButton);body.append(actions);openDialog('使用说明 · はじめに',body)}
const guideButton=$('#guide-open');if(guideButton)guideButton.onclick=showGuide;
 const quickGuide=textEl('aside','','quick-guide');quickGuide.hidden=Boolean(load('takagi-guide-seen-v1'));const quickWords=document.createElement('span');quickWords.append(textEl('strong','第一次来？'),textEl('small','聊天默认使用 DeepSeek Flash，在线服务异常时自动使用本地陪伴。也可以去“诗集分享”写下放学后的句子。'));const quickOpen=textEl('button','查看说明');quickOpen.type='button';quickOpen.onclick=showGuide;const quickClose=textEl('button','知道了','quick-guide-close');quickClose.type='button';quickClose.onclick=()=>{quickGuide.hidden=true;save('takagi-guide-seen-v1','yes')};quickGuide.append(quickWords,quickOpen,quickClose);$('.chat-scroll').before(quickGuide);
$('#access-open').onclick=()=>{const body=document.createElement('div');const online=!['localhost','127.0.0.1'].includes(location.hostname);body.append(textEl('h3','访问范围'),textEl('p','网站已公开，朋友获得网址后可以直接打开，无需登录。'),textEl('h3','当前状态'),textEl('p',online?'正在访问公开发布的站点。':'当前是本地预览。'),textEl('h3','会话与隐私'),textEl('p','在线回复会把本轮消息、最近 12 条对话和个性设置发送给 DeepSeek。你主动附在聊天中的图片仅随该轮发送。API 密钥只保存在 Netlify Function 的环境变量中。短期对话保存在当前标签页会话，刷新后仍可承接，关闭标签页后清除。称呼、场景、游戏和音乐偏好以及青春诗笺保存在当前浏览器。'),textEl('h3','密码有效范围'),textEl('p','密码在成功校验后仅保存在当前标签页。刷新页面仍可继续使用；关闭标签页或点击聊天区的“清除”后需要重新输入。服务器会在每次请求时重新核对 ADMIN_PASSWORD。'),textEl('h3','当前调用限制'),textEl('p','当前部署未设置两小时有效期、个人调用次数或每日额度。现有保护包括同源校验、每条最多 1200 字、最多 12 条短期上下文以及请求大小和等待时间限制。DeepSeek 或 Netlify 自身的账户额度仍会生效。GPT API 当前暂不支持。'));openDialog('访问权限',body)};
$('#share-site').onclick=async()=>{const data={title:'放学后 · 高木同学',text:'一个可以聊天、学习陪伴和体验校园情景的同人互动网页。',url:location.origin};try{if(navigator.share){await navigator.share(data);speak('已经打开分享啦。你会先发给谁呢？')}else{await navigator.clipboard.writeText(data.url);speak('网址复制好了。别只复制，记得真的发出去哦。')}}catch(error){if(error?.name!=='AbortError')speak('没有复制成功，可以直接从地址栏复制网址。')}};
if(document.modelContext?.registerTool){const life=new AbortController();const register=(name,description,inputSchema,execute)=>Promise.resolve(document.modelContext.registerTool({name,description,inputSchema,annotations:{readOnlyHint:false},execute},{signal:life.signal})).catch(()=>{});try{register('set_character_pose','切换高木同学的展示取景', {type:'object',properties:{pose:{type:'string',enum:['daily','close','portrait','wide']}},required:['pose'],additionalProperties:false},v=>pose(v?.pose));register('select_scene','选择高木同学的互动场景', {type:'object',properties:{scene:{type:'string',enum:['classroom','cafeteria','study','rain','valentine','whiteDay','festival']}},required:['scene'],additionalProperties:false},v=>setScene(v?.scene));register('interact_with_character','触发当前场景中的一个可用互动', {type:'object',properties:{action:{type:'string'}},required:['action'],additionalProperties:false},v=>{if(!scenes[activeScene].actions.some(a=>a[0]===v?.action))throw Error('此场景没有这个互动');return interact(v.action)});addEventListener('pagehide',()=>life.abort(),{once:true})}catch{}}

const continuityScript=document.createElement('script');continuityScript.src='./js/continuity.js?v=62';document.body.append(continuityScript);
const loadExtras=()=>{const extrasScript=document.createElement('script');extrasScript.src='./js/extras.js?v=62';document.body.append(extrasScript)};
const queueExtras=()=>{'requestIdleCallback' in window?requestIdleCallback(loadExtras,{timeout:900}):setTimeout(loadExtras,250)};
document.readyState==='complete'?queueExtras():addEventListener('load',queueExtras,{once:true});
