(() => {
  const memories = [
    ['互动 01','放学后，被看穿的一瞬间'],['互动 02','话还没说完，表情先承认了'],['互动 03','她好像早就知道答案'],['互动 04','走廊里短短的一次停步'],['互动 05','又输给她一次'],
    ['互动 06','平常日子里的小小胜负'],['互动 07','视线碰到一起的时候'],['互动 08','没能藏住的反应'],['互动 09','下一句会说什么呢'],['互动 10','今天也被她捉弄了'],
    ['教室互动','教室 · 放学后的两个人'],['雨天共伞','雨天 · 伞下的距离'],['走廊捉弄','走廊 · 熟悉的小玩笑'],['夏日祭典','夏日祭 · 灯火与人群'],['海边夕阳','海边 · 日落之前'],
    ['舞台互动','舞台 · 意外的目光'],['雨中互动','雨声 · 没说出口的话'],['图书阅读','图书室 · 翻过同一页'],['教室捉弄','教室 · 她的又一次胜利'],['冬夜互动','冬夜 · 呼吸变成白雾'],
    ['轻微脸红','细小的表情也会被记住'],['捂嘴害羞','笑意藏在指尖后面'],['低头脸红','低头的几秒钟'],['祭典害羞','祭典夜里的心事'],['书本遮脸','书页挡不住的反应'],
    ['笑着脸红','笑着装作若无其事'],['惊讶脸红','突然靠近的一刻'],['夕阳侧目','夕阳把侧脸染得很轻'],['冬日害羞','冬天也有温热的瞬间'],['捂脸反应','这次真的被说中了']
  ].map(([title,caption],index)=>({title,caption,src:`./assets/memories/memory-${String(index+1).padStart(2,'0')}.png`}));
  const spots = [
    [130,135,320,220,-5],[535,80,250,280,4],[890,195,350,225,-2],[1340,90,255,300,4],[1735,210,335,215,-4],
    [300,440,240,300,3],[710,430,320,215,-5],[1115,520,235,290,4],[1485,445,350,220,2],[1950,500,235,290,-3],
    [70,790,340,220,-3],[505,790,240,290,5],[880,865,330,215,2],[1285,755,250,305,-4],[1690,860,340,220,4],
    [260,1160,245,300,-4],[655,1175,350,220,3],[1080,1135,240,290,-2],[1430,1220,320,215,5],[1880,1135,250,300,-4],
    [65,1450,310,215,3],[455,1510,240,285,-5],[810,1435,330,220,4],[1190,1505,245,295,-3],[1550,1495,340,215,2],
    [1945,1440,245,295,5],[200,1770,320,215,-3],[675,1740,245,290,4],[1120,1730,340,215,-4],[1650,1750,325,220,3]
  ];
  const shell=textEl('section','','memory-shell');shell.id='memories';
  const summary=textEl('button','','memory-summary');summary.type='button';summary.setAttribute('aria-haspopup','dialog');
  const mark=textEl('span','想','memory-summary-mark');mark.setAttribute('aria-hidden','true');
  const copy=textEl('span','','memory-summary-copy');const summaryDetail=textEl('small','思い出の雨 · 拖动浏览 30 个片段');copy.append(textEl('strong','星夜回忆录'),summaryDetail);
  const count=textEl('span','30 张','memory-summary-count');const arrow=textEl('span','↗','memory-summary-arrow');arrow.setAttribute('aria-hidden','true');summary.append(mark,copy,count,arrow);shell.append(summary);
  const dialog=document.createElement('dialog');dialog.className='memory-modal';dialog.setAttribute('aria-labelledby','memory-title');
  const frame=textEl('div','','memory-frame');
  const ambience=textEl('div','','memory-ambience');ambience.setAttribute('aria-hidden','true');ambience.append(textEl('span','','memory-stars'),textEl('span','','memory-glow'),textEl('span','','memory-meteor memory-meteor-one'),textEl('span','','memory-meteor memory-meteor-two'));
  const header=textEl('header','','memory-header');const heading=textEl('div','','memory-heading');const title=textEl('h2','思い出の雨');title.id='memory-title';heading.append(title,textEl('p','星夜回忆录 · DRIFT THROUGH THE MEMORIES'));
  const close=textEl('button','×','memory-close');close.type='button';close.setAttribute('aria-label','关闭星夜回忆录');header.append(heading,close);
  const viewport=textEl('div','','memory-viewport');viewport.tabIndex=0;viewport.setAttribute('aria-label','可拖动和缩放的照片回忆墙');const world=textEl('div','','memory-world');viewport.append(world);
  const help=textEl('p','拖动浏览 · 滚轮或双指缩放 · 点击照片放大','memory-help');
  const controls=textEl('div','','memory-controls');const zoomOut=textEl('button','−');const zoomValue=textEl('span','100%');const zoomIn=textEl('button','＋');const reset=textEl('button','复位');[zoomOut,zoomIn,reset].forEach(button=>button.type='button');zoomOut.setAttribute('aria-label','缩小回忆墙');zoomIn.setAttribute('aria-label','放大回忆墙');reset.setAttribute('aria-label','复位回忆墙');controls.append(zoomOut,zoomValue,zoomIn,reset);
  const personalTools=textEl('div','','memory-personal-tools');const addPhotos=textEl('button','＋ 加入我的照片');addPhotos.type='button';const picker=document.createElement('input');picker.type='file';picker.accept='image/jpeg,image/png,image/webp';picker.multiple=true;picker.hidden=true;const personalStatus=textEl('small','最多 12 张，单张不超过 8 MB · 点个人照片右上角 × 删除 · 仅保存在当前浏览器');personalStatus.setAttribute('role','status');personalTools.append(addPhotos,picker,personalStatus);
  const lightbox=textEl('div','','memory-lightbox');lightbox.hidden=true;lightbox.setAttribute('role','dialog');lightbox.setAttribute('aria-modal','true');const figure=document.createElement('figure');const lightboxClose=textEl('button','×','memory-lightbox-close');lightboxClose.type='button';lightboxClose.setAttribute('aria-label','关闭大图');const big=document.createElement('img');big.alt='';const caption=document.createElement('figcaption');figure.append(lightboxClose,big,caption);lightbox.append(figure);
  frame.append(ambience,header,viewport,personalTools,help,controls,lightbox);dialog.append(frame);document.body.append(dialog);
  const anchor=document.querySelector('.omikuji-shell')||document.querySelector('.leisure')||document.querySelector('.terms-preview');anchor.after(shell);
  let personalMemories=[],personalUrls=[],memoryDatabase=null,WORLD_HEIGHT=2020;
  function renderDrop(item,spot,index,personal=false){const [left,top,width,height,rotation]=spot;const card=textEl('div','',`memory-drop${personal?' memory-drop-personal':''}`);card.tabIndex=0;card.setAttribute('role','button');card.style.cssText=`left:${left}px;top:${top}px;width:${width}px;height:${height}px;--memory-r:${rotation}deg;--memory-z:${2+index%5}`;card.setAttribute('aria-label',`${item.title}：${item.caption}`);const image=document.createElement('img');image.src=item.src;image.alt=item.caption;image.loading='lazy';card.append(image,textEl('span',item.title));card.onclick=event=>{if(!event.target.closest('.memory-drop-remove'))openPhoto(item)};card.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('.memory-drop-remove')){event.preventDefault();openPhoto(item)}};if(personal){const remove=textEl('button','×','memory-drop-remove');remove.type='button';remove.setAttribute('aria-label',`删除${item.title}`);remove.title='从回忆录中删除';remove.onclick=event=>{event.stopPropagation();removePersonalMemory(item.id)};card.append(remove)}world.append(card)}
  memories.forEach((item,index)=>renderDrop(item,spots[index],index));
  function personalSpot(index){const col=index%4,row=Math.floor(index/4);return[145+col*520,2140+row*345,310+(index%3)*18,225+(index%2)*28,[-4,3,-2,5][index%4]]}
  function updatePersonalMemories(){personalUrls.forEach(url=>URL.revokeObjectURL(url));personalUrls=[];world.querySelectorAll('.memory-drop-personal,.memory-personal-label').forEach(node=>node.remove());if(personalMemories.length){const label=textEl('div','あなたの思い出 · 你的照片','memory-personal-label');label.style.cssText='left:150px;top:2055px';world.append(label)}personalMemories.forEach((record,index)=>{const src=URL.createObjectURL(record.blob);personalUrls.push(src);renderDrop({id:record.id,title:(record.name||`我的照片 ${index+1}`).replace(/\.[^.]+$/,''),caption:'你加入的回忆',src},personalSpot(index),30+index,true)});WORLD_HEIGHT=personalMemories.length?2220+Math.ceil(personalMemories.length/4)*345:2020;world.style.height=WORLD_HEIGHT+'px';count.textContent=`${30+personalMemories.length} 张`;summaryDetail.textContent=`思い出の雨 · 拖动浏览 ${30+personalMemories.length} 个片段`;if(dialog.open)paint()}
  let x=0,y=0,scale=1,down=false,startX=0,startY=0,originX=0,originY=0,moved=false,dropCandidate=null,pointers=new Map(),pinchDistance=0,pinchScale=1;
  function bounds(){const width=2200*scale,height=WORLD_HEIGHT*scale,viewWidth=viewport.clientWidth,viewHeight=viewport.clientHeight;x=Math.min(180,Math.max(viewWidth-width-180,x));y=Math.min(150,Math.max(viewHeight-height-150,y))}
  function paint(){bounds();world.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`;zoomValue.textContent=Math.round(scale*100)+'%'}
  function zoomAt(next,cx=viewport.clientWidth/2,cy=viewport.clientHeight/2){next=Math.max(.38,Math.min(1.75,next));const rect=viewport.getBoundingClientRect(),localX=cx-rect.left,localY=cy-rect.top,worldX=(localX-x)/scale,worldY=(localY-y)/scale;x=localX-worldX*next;y=localY-worldY*next;scale=next;paint()}
  function resetView(){const fit=Math.max(.42,Math.min(.82,(viewport.clientWidth-40)/2200,(viewport.clientHeight-40)/2020));scale=fit;x=(viewport.clientWidth-2200*scale)/2;y=(viewport.clientHeight-2020*scale)/2;paint()}
  function openPhoto(item){if(moved)return;big.src=item.src;big.alt=item.caption;caption.textContent=`${item.title} · ${item.caption}`;lightbox.hidden=false;requestAnimationFrame(()=>lightbox.classList.add('is-visible'));lightboxClose.focus()}
  function closePhoto(){lightbox.classList.remove('is-visible');setTimeout(()=>{lightbox.hidden=true;big.removeAttribute('src')},180)}
  function openMemories(){if(!dialog.open)dialog.showModal();document.body.classList.add('memory-modal-open');setTimeout(()=>{resetView();viewport.focus()},60)}
  function closeMemories(){if(!lightbox.hidden){closePhoto();return}if(dialog.open)dialog.close()}
  function openMemoryDatabase(){return new Promise((resolve,reject)=>{try{const request=indexedDB.open('takagi-personal-memories',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('photos'))request.result.createObjectStore('photos',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}catch(error){reject(error)}})}
  function memoryStore(mode='readonly'){return memoryDatabase.transaction('photos',mode).objectStore('photos')}
  function readPersonalMemories(){return new Promise((resolve,reject)=>{const request=memoryStore().getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error)})}
  function savePersonalMemory(record){return new Promise((resolve,reject)=>{const request=memoryStore('readwrite').put(record);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}
  function deletePersonalMemory(id){return new Promise((resolve,reject)=>{const request=memoryStore('readwrite').delete(id);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}
  async function removePersonalMemory(id){const record=personalMemories.find(item=>item.id===id);personalMemories=personalMemories.filter(item=>item.id!==id);updatePersonalMemories();try{if(memoryDatabase)await deletePersonalMemory(id);personalStatus.textContent=`已删除${record?.name||'这张照片'}。其余照片仍保存在当前浏览器。`}catch{personalStatus.textContent='画面已删除，浏览器未能保存此次操作。'}}
  addPhotos.onclick=()=>picker.click();
  picker.onchange=async()=>{const picked=Array.from(picker.files||[]);picker.value='';if(!picked.length)return;const room=Math.max(0,12-personalMemories.length),accepted=[];let rejected=0;for(const file of picked.slice(0,room)){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){rejected++;continue}accepted.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,name:file.name,blob:file,createdAt:Date.now()})}if(!accepted.length){personalStatus.textContent=room?'没有可加入的图片。请选择单张不超过 8 MB 的 JPG、PNG 或 WebP。':'最多保留 12 张个人照片。';return}personalMemories.push(...accepted);updatePersonalMemories();let saved=0;if(memoryDatabase){for(const record of accepted){try{await savePersonalMemory(record);saved++}catch{}}}personalStatus.textContent=`已加入 ${accepted.length} 张，向下拖动即可看到。${memoryDatabase&&saved===accepted.length?' 已保存在当前浏览器。':' 刷新后可能无法保留。'}${rejected||picked.length>room?' 部分图片因格式、大小或数量限制未加入。':''}`};
  summary.onclick=openMemories;close.onclick=closeMemories;const nav=document.querySelector('#memories-open');if(nav)nav.onclick=openMemories;
  zoomIn.onclick=()=>zoomAt(scale*1.18);zoomOut.onclick=()=>zoomAt(scale/1.18);reset.onclick=resetView;
  viewport.addEventListener('wheel',event=>{event.preventDefault();zoomAt(scale*(event.deltaY>0?.9:1.1),event.clientX,event.clientY)},{passive:false});
  viewport.onpointerdown=event=>{pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});moved=false;if(pointers.size===1){dropCandidate=event.target.closest?.('.memory-drop')||null;if(!dropCandidate)viewport.setPointerCapture(event.pointerId);down=true;startX=event.clientX;startY=event.clientY;originX=x;originY=y}else if(pointers.size===2){dropCandidate=null;viewport.setPointerCapture(event.pointerId);const values=[...pointers.values()];pinchDistance=Math.hypot(values[0].x-values[1].x,values[0].y-values[1].y);pinchScale=scale}viewport.classList.add('is-dragging')};
  viewport.onpointermove=event=>{if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2){moved=true;const values=[...pointers.values()],distance=Math.hypot(values[0].x-values[1].x,values[0].y-values[1].y),centerX=(values[0].x+values[1].x)/2,centerY=(values[0].y+values[1].y)/2;zoomAt(pinchScale*distance/pinchDistance,centerX,centerY)}else if(down){const dx=event.clientX-startX,dy=event.clientY-startY;if(Math.hypot(dx,dy)>6){moved=true;if(dropCandidate){viewport.setPointerCapture(event.pointerId);dropCandidate=null}}x=originX+dx;y=originY+dy;paint()}};
  viewport.onpointerup=viewport.onpointercancel=event=>{pointers.delete(event.pointerId);if(!pointers.size){down=false;dropCandidate=null;viewport.classList.remove('is-dragging')}else if(pointers.size===1){const remaining=[...pointers.values()][0];startX=remaining.x;startY=remaining.y;originX=x;originY=y}};
  lightbox.onclick=event=>{if(event.target===lightbox)closePhoto()};lightboxClose.onclick=closePhoto;dialog.addEventListener('click',event=>{if(event.target===dialog)closeMemories()});dialog.addEventListener('cancel',event=>{event.preventDefault();closeMemories()});dialog.addEventListener('close',()=>document.body.classList.remove('memory-modal-open'));
  window.addEventListener('resize',()=>{if(dialog.open)resetView()});
  openMemoryDatabase().then(async db=>{memoryDatabase=db;personalMemories=(await readPersonalMemories()).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0)).slice(0,12);updatePersonalMemories()}).catch(()=>{personalStatus.textContent='此浏览器无法长期保存照片，本次打开期间仍可使用。'});
})();
